export const minimalPairs = [
  {
    category: '学習中の日本人',
    pairs: [
      {
        word1: 'road',
        word2: 'load',
        ipa1: '/roʊd/',
        ipa2: '/loʊd/',
        audio1: require('../assets/audio/road.mp3'),
        audio2: require('../assets/audio/load.mp3'),
      },
      {
        word1: 'light',
        word2: 'right',
        ipa1: '/laɪt/',
        ipa2: '/raɪt/',
        audio1: require('../assets/audio/light.mp3'),
        audio2: require('../assets/audio/right.mp3'),
      },
      {
        word1: 'ban',
        word2: 'van',
        ipa1: '/bæn/',
        ipa2: '/væn/',
        audio1: require('../assets/audio/ban.mp3'),
        audio2: require('../assets/audio/van.mp3'),
      },
      {
        word1: 'sink',
        word2: 'think',
        ipa1: '/sɪŋk/',
        ipa2: '/θɪŋk/',
        audio1: require('../assets/audio/sink.mp3'),
        audio2: require('../assets/audio/think.mp3'),
      },
      {
        word1: 'cat',
        word2: 'cut',
        ipa1: '/kæt/',
        ipa2: '/kʌt/',
        audio1: require('../assets/audio/cat.mp3'),
        audio2: require('../assets/audio/cut.mp3'),
      },
      {
        word1: 'sheep',
        word2: 'ship',
        ipa1: '/ʃiːp/',
        ipa2: '/ʃɪp/',
        audio1: require('../assets/audio/sheep.mp3'),
        audio2: require('../assets/audio/ship.mp3'),
      },
    ],
  },
  {
    category: '汉语学习者',
    pairs: [
      {
        word1: 'thin',
        word2: 'sin',
        ipa1: '/θɪn/',
        ipa2: '/sɪn/',
        audio1: require('../assets/audio/thin.mp3'),
        audio2: require('../assets/audio/sin.mp3'),
      },
      {
        word1: 'vine',
        word2: 'wine',
        ipa1: '/vaɪn/',
        ipa2: '/waɪn/',
        audio1: require('../assets/audio/vine.mp3'),
        audio2: require('../assets/audio/wine.mp3'),
      },
      {
        word1: 'right',
        word2: 'light',
        ipa1: '/raɪt/',
        ipa2: '/laɪt/',
        audio1: require('../assets/audio/right.mp3'),
        audio2: require('../assets/audio/light.mp3'),
      },
      {
        word1: 'beat',
        word2: 'bit',
        ipa1: '/biːt/',
        ipa2: '/bɪt/',
        audio1: require('../assets/audio/beat.mp3'),
        audio2: require('../assets/audio/bit.mp3'),
      },
      {
        word1: 'pool',
        word2: 'pull',
        ipa1: '/puːl/',
        ipa2: '/pʊl/',
        audio1: require('../assets/audio/pool.mp3'),
        audio2: require('../assets/audio/pull.mp3'),
      },
    ],
  },
  {
    category: 'คนไทยที่เป็นผู้เรียน',
    pairs: [
      {
        word1: 'thin',
        word2: 'tin',
        ipa1: '/θɪn/',
        ipa2: '/tɪn/',
        audio1: require('../assets/audio/thin.mp3'),
        audio2: require('../assets/audio/tin.mp3'),
      },
      {
        word1: 'then',
        word2: 'den',
        ipa1: '/ðɛn/',
        ipa2: '/dɛn/',
        audio1: require('../assets/audio/then.mp3'),
        audio2: require('../assets/audio/den.mp3'),
      },
      {
        word1: 'vine',
        word2: 'fine',
        ipa1: '/vaɪn/',
        ipa2: '/faɪn/',
        audio1: require('../assets/audio/vine.mp3'),
        audio2: require('../assets/audio/fine.mp3'),
      },
      {
        word1: 'zip',
        word2: 'sip',
        ipa1: '/zɪp/',
        ipa2: '/sɪp/',
        audio1: require('../assets/audio/zip.mp3'),
        audio2: require('../assets/audio/sip.mp3'),
      },
      {
        word1: 'right',
        word2: 'light',
        ipa1: '/raɪt/',
        ipa2: '/laɪt/',
        audio1: require('../assets/audio/right.mp3'),
        audio2: require('../assets/audio/light.mp3'),
      },
    ],
  },
  {
    category: 'Hablantes de español',
    pairs: [
      {
        word1: 'sheep',
        word2: 'ship',
        ipa1: '/ʃiːp/',
        ipa2: '/ʃɪp/',
        audio1: require('../assets/audio/sheep.mp3'),
        audio2: require('../assets/audio/ship.mp3'),
      },
      {
        word1: 'cut',
        word2: 'cot',
        ipa1: '/kʌt/',
        ipa2: '/kɑːt/',
        audio1: require('../assets/audio/cut.mp3'),
        audio2: require('../assets/audio/cot.mp3'),
      },
      {
        word1: 'bad',
        word2: 'bed',
        ipa1: '/bæd/',
        ipa2: '/bɛd/',
        audio1: require('../assets/audio/bad.mp3'),
        audio2: require('../assets/audio/bed.mp3'),
      },
      {
        word1: 'bow',
        word2: 'vow',
        ipa1: '/boʊ/',
        ipa2: '/vaʊ/',
        audio1: require('../assets/audio/bow.mp3'),
        audio2: require('../assets/audio/vow.mp3'),
      },
      {
        word1: 'thin',
        word2: 'sin',
        ipa1: '/θɪn/',
        ipa2: '/sɪn/',
        audio1: require('../assets/audio/thin.mp3'),
        audio2: require('../assets/audio/sin.mp3'),
      },
    ],
  },
  {
    category: 'المتحدثون باللغة العربية الذين يتعلمون',
    pairs: [
      {
        word1: 'pat',
        word2: 'bat',
        ipa1: '/pæt/',
        ipa2: '/bæt/',
        audio1: require('../assets/audio/pat.mp3'),
        audio2: require('../assets/audio/bat.mp3'),
      },
      {
        word1: 'fan',
        word2: 'van',
        ipa1: '/fæn/',
        ipa2: '/væn/',
        audio1: require('../assets/audio/fan.mp3'),
        audio2: require('../assets/audio/van.mp3'),
      },
      {
        word1: 'sin',
        word2: 'sing',
        ipa1: '/sɪn/',
        ipa2: '/sɪŋ/',
        audio1: require('../assets/audio/sin.mp3'),
        audio2: require('../assets/audio/sing.mp3'),
      },
      {
        word1: 'jam',
        word2: 'Zhām',
        ipa1: '/dʒæm/',
        ipa2: '/ʒɑːm/',
        audio1: require('../assets/audio/jam.mp3'),
        audio2: require('../assets/audio/zham.mp3'),
      },
      {
        word1: 'leaf',
        word2: 'leave',
        ipa1: '/liːf/',
        ipa2: '/liːv/',
        audio1: require('../assets/audio/leaf.mp3'),
        audio2: require('../assets/audio/leave.mp3'),
      },
    ],
  },
  {
    category: 'Русские, которые учатся',
    pairs: [
      {
        word1: 'wine',
        word2: 'vine',
        ipa1: '/waɪn/',
        ipa2: '/vaɪn/',
        audio1: require('../assets/audio/wine.mp3'),
        audio2: require('../assets/audio/vine.mp3'),
      },
      {
        word1: 'beat',
        word2: 'bit',
        ipa1: '/biːt/',
        ipa2: '/bɪt/',
        audio1: require('../assets/audio/beat.mp3'),
        audio2: require('../assets/audio/bit.mp3'),
      },
      {
        word1: 'bad',
        word2: 'bed',
        ipa1: '/bæd/',
        ipa2: '/bɛd/',
        audio1: require('../assets/audio/bad.mp3'),
        audio2: require('../assets/audio/bed.mp3'),
      },
      {
        word1: 'calm',
        word2: 'come',
        ipa1: '/kɑːm/',
        ipa2: '/kʌm/',
        audio1: require('../assets/audio/calm.mp3'),
        audio2: require('../assets/audio/come.mp3'),
      },
      {
        word1: 'leaf',
        word2: 'leave',
        ipa1: '/liːf/',
        ipa2: '/liːv/',
        audio1: require('../assets/audio/leaf.mp3'),
        audio2: require('../assets/audio/leave.mp3'),
      },
    ],
  },
  {
    category: '학습하는 한국인들',
    pairs: [
      {
        word1: 'road',
        word2: 'load',
        ipa1: '/roʊd/',
        ipa2: '/loʊd/',
        audio1: require('../assets/audio/road.mp3'),
        audio2: require('../assets/audio/load.mp3'),
      },
      {
        word1: 'fan',
        word2: 'pan',
        ipa1: '/fæn/',
        ipa2: '/pæn/',
        audio1: require('../assets/audio/fan.mp3'),
        audio2: require('../assets/audio/pan.mp3'),
      },
      {
        word1: 'vain',
        word2: 'bane',
        ipa1: '/veɪn/',
        ipa2: '/beɪn/',
        audio1: require('../assets/audio/vain.mp3'),
        audio2: require('../assets/audio/bane.mp3'),
      },
      {
        word1: 'seat',
        word2: 'sheet',
        ipa1: '/siːt/',
        ipa2: '/ʃiːt/',
        audio1: require('../assets/audio/seat.mp3'),
        audio2: require('../assets/audio/sheet.mp3'),
      },
      {
        word1: 'zeal',
        word2: 'seal',
        ipa1: '/ziːl/',
        ipa2: '/siːl/',
        audio1: require('../assets/audio/zeal.mp3'),
        audio2: require('../assets/audio/seal.mp3'),
      },
    ],
  },
  {
    category: 'हिंदी/اردو',
    pairs: [
      {
        word1: 'vine',
        word2: 'wine',
        ipa1: '/vaɪn/',
        ipa2: '/waɪn/',
        audio1: require('../assets/audio/vine.mp3'),
        audio2: require('../assets/audio/wine.mp3'),
      },
      {
        word1: 'thin',
        word2: 'tin',
        ipa1: '/θɪn/',
        ipa2: '/tɪn/',
        audio1: require('../assets/audio/thin.mp3'),
        audio2: require('../assets/audio/tin.mp3'),
      },
      {
        word1: 'then',
        word2: 'den',
        ipa1: '/ðɛn/',
        ipa2: '/dɛn/',
        audio1: require('../assets/audio/then.mp3'),
        audio2: require('../assets/audio/den.mp3'),
      },
      {
        word1: 'zeal',
        word2: 'seal',
        ipa1: '/ziːl/',
        ipa2: '/siːl/',
        audio1: require('../assets/audio/zeal.mp3'),
        audio2: require('../assets/audio/seal.mp3'),
      },
      {
        word1: 'bat',
        word2: 'bet',
        ipa1: '/bæt/',
        ipa2: '/bɛt/',
        audio1: require('../assets/audio/bat.mp3'),
        audio2: require('../assets/audio/bet.mp3'),
      },
    ],
  },
  {
    category: 'Português/Brasileiro',
    pairs: [
      {
        word1: 'beat',
        word2: 'bit',
        ipa1: '/biːt/',
        ipa2: '/bɪt/',
        audio1: require('../assets/audio/beat.mp3'),
        audio2: require('../assets/audio/bit.mp3'),
      },
      {
        word1: 'thin',
        word2: 'tin',
        ipa1: '/θɪn/',
        ipa2: '/tɪn/',
        audio1: require('../assets/audio/thin.mp3'),
        audio2: require('../assets/audio/tin.mp3'),
      },
      {
        word1: 'ship',
        word2: 'chip',
        ipa1: '/ʃɪp/',
        ipa2: '/tʃɪp/',
        audio1: require('../assets/audio/ship.mp3'),
        audio2: require('../assets/audio/chip.mp3'),
      },
    ],
  },
  {
    category: 'Tiếng Việt',
    pairs: [
      {
        word1: 'sheep',
        word2: 'sip',
        ipa1: '/ʃiːp/',
        ipa2: '/sɪp/',
        audio1: require('../assets/audio/sheep.mp3'),
        audio2: require('../assets/audio/sip.mp3'),
      },
      {
        word1: 'leap',
        word2: 'leave',
        ipa1: '/liːp/',
        ipa2: '/liːv/',
        audio1: require('../assets/audio/leap.mp3'),
        audio2: require('../assets/audio/leave.mp3'),
      },
    ],
  },
  {
    category: 'Türkçe konuşanlar',
    pairs: [
      {
        word1: 'think',
        word2: 'sink',
        ipa1: '/θɪŋk/',
        ipa2: '/sɪŋk/',
        audio1: require('../assets/audio/think.mp3'),
        audio2: require('../assets/audio/sink.mp3'),
      },
      {
        word1: 'west',
        word2: 'vest',
        ipa1: '/wɛst/',
        ipa2: '/vɛst/',
        audio1: require('../assets/audio/west.mp3'),
        audio2: require('../assets/audio/vest.mp3'),
      },
    ],
  },
  {
    category: 'پارسی ها',
    pairs: [
      {
        word1: 'think',
        word2: 'sink',
        ipa1: '/θɪŋk/',
        ipa2: '/sɪŋk/',
        audio1: require('../assets/audio/think.mp3'),
        audio2: require('../assets/audio/sink.mp3'),
      },
      {
        word1: 'sheep',
        word2: 'sip',
        ipa1: '/ʃiːp/',
        ipa2: '/sɪp/',
        audio1: require('../assets/audio/sheep.mp3'),
        audio2: require('../assets/audio/sip.mp3'),
      },
    ],
  },
  {
    category: '講廣東話嘅人',
    pairs: [
      {
        word1: 'right',
        word2: 'light',
        ipa1: '/raɪt/',
        ipa2: '/laɪt/',
        audio1: require('../assets/audio/right.mp3'),
        audio2: require('../assets/audio/light.mp3'),
      },
      {
        word1: 'vine',
        word2: 'fine',
        ipa1: '/vaɪn/',
        ipa2: '/faɪn/',
        audio1: require('../assets/audio/vine.mp3'),
        audio2: require('../assets/audio/fine.mp3'),
      },
    ],
  },
  {
    category: 'Orang Indonesia',
    pairs: [
      {
        word1: 'think',
        word2: 'sink',
        ipa1: '/θɪŋk/',
        ipa2: '/sɪŋk/',
        audio1: require('../assets/audio/think.mp3'),
        audio2: require('../assets/audio/sink.mp3'),
      },
      {
        word1: 'sheep',
        word2: 'sip',
        ipa1: '/ʃiːp/',
        ipa2: '/sɪp/',
        audio1: require('../assets/audio/sheep.mp3'),
        audio2: require('../assets/audio/sip.mp3'),
      },
    ],
  },
];
