module.exports = {
  preset: 'jest-expo',
  setupFiles: ['./jest.setup.js'],
  collectCoverage: true,
  collectCoverageFrom: [
    'components/TimePracticedBar.tsx',
    'components/ThemedText.tsx',
    'src/context/PairProgressContext.tsx',
    'src/storage/progressStorage.ts',
    'app/(tabs)/*.tsx',
    '!**/*.d.ts',
    '!**/node_modules/**',
    '!**/__tests__/**',
    '!**/*.test.{ts,tsx}',
    '!**/jest.setup.js',
    '!**/test/**',
    '!components/AccuracyTimeChart.tsx',
    '!components/ThemedView.tsx',
    '!components/HapticTab.tsx',
    '!**/types.ts',
    '!**/sessionStorage.ts',
  ],
  coverageReporters: ['text', 'lcov'],
  testPathIgnorePatterns: ['/node_modules/', '/dist/', '/e2e/'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
};
