export const englishTranslations = {
    home: 'Home',
    results: 'Results',
    info: 'Info',
    settings: 'Settings',
    practicePairs: 'Practice',
    playAudio: 'Play Audio',
    accuracyTrend: 'Recent Accuracy Trend',
    timePracticed: 'Recent Practice Time',
    min: 'min',
    weightedAverage: 'Weighted Average',
    total: 'Total',
    configureApp: 'Configure App',
    language: 'Language',
    voiceSelection: 'Voice Selection',
    systemDefault: 'System Default',
    loadingVoices: 'Loading voices...',
    noVoicesAvailable: 'No voices available',
    refresh: 'Refresh',
    appInfo: 'App Info',
    version: 'Version',
    build: 'Build',
    usAccentFemale: '🇺🇸 US Accent (Female)',
    ukAccentMale: '🇬🇧 UK Accent (Male)',
    americanEnglish: 'American English',
    britishEnglish: 'British English',
    appearance: 'Appearance',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    systemMode: 'System Settings',
    useEnglishUI: 'Use English UI',
    englishUIDescription: 'Display interface in English',
    titleOne: 'Train Your Ears, Transform Your Listening!',
    infoOne:
      'Many English learners struggle to distinguish between "ship" and "sheep" or "light" and "right". This app helps you train your ears to hear these subtle differences.',
    titleTwo: 'Goal',
    infoTwo:
      'Aim to practice each contrast for at least 60 minutes. It may seem difficult at first, but your brain will adapt with practice!',
    titleThree: 'How It Works',
    infoThree:
      '• Tap "Play Audio" to hear a word\n• Select the word you heard\n• Get immediate feedback\n• Track your progress over time',
    voicesAvailable: 'voices available',
    voiceActive: 'active',
    theWordWas: 'The word was',
    listenAgain: 'Listen Again',
    correct: 'Correct',
    incorrect: 'Incorrect',
    placementTest: 'Placement Test',
    retakePlacement: 'Retake on next practice session',
    skip: 'Skip',
    todaySession: "Today's session",
    dailyGoal: 'Daily goal',
    levelOf: 'Contrast level',
    mastered: 'Contrast mastered',
    levelUnlocked: 'This contrast leveled up!',
    levelCriteria: 'Answer correctly at increasing speeds to level up this contrast.',
    pairsMastered: 'Contrasts Mastered',
    levelsCompleted: 'Contrast Levels Completed',
    placementDescription: 'Determine your starting level',
    placementCompleted: 'Completed',
    placementResetConfirm: 'The placement test will run when you return to the Practice tab.',
    audioError: 'Audio Error',
    audioInitializing: 'Audio system is still initializing. Please try again.',
    hr: 'hr',
    helpTitle: 'How to practice',
    helpBody: 'Listen to the word and tap what you hear.',
    helpTipPracticeTime: 'Practice each contrast for about 60 minutes',
    helpTipSpeedIncrease: 'Speed increases as you level up',
    helpTipFocusSounds: 'Focus on hearing the sound difference',
    helpButton: 'Got it',
    onboardingTitle: 'Welcome to Soundwise',
    onboardingCTA: 'Start Listening',
    onboardingBullet1: 'Train your ear.',
    onboardingBullet2: 'Listen to the word.',
    onboardingBullet3: 'Choose which word you heard.',
    onboardingBullet4: 'Practice adapts to your progress.',
    onboardingBullet5: 'No microphone needed.',
    practiceThisNext: 'Practice this next',
    practiceThisNextReason: 'Your recent accuracy is lower for this contrast.',
    practiceThisNextReasonNew: "You haven't practiced this contrast yet.",
    practiceThisNextEmpty: 'Practice a few contrasts to get a recommendation.',
    noPairsFound: 'No contrasts found for',
    whichWordDidYouHear: 'Which word did you hear?',
    compareTheTwoWords: 'Compare the two words',
    play: 'Play',
    practicePair: 'Practice pair',
    chooseAnotherExample: 'Choose another example',
    loading: 'Loading…',
    listenForSoundDifference: 'Listen for the sound difference.',
    contrastMovedToLevel: 'This contrast moved to Level',
    tips: 'Tips',
    closeHelp: 'Close help',
    helpLabel: 'Help',
    doubleTapToSelectWord: 'Double tap to select this word as your answer',
    doubleTapToHearAWord: 'Double tap to hear a word',
    doubleTapToHear: 'Double tap to hear',
    correctYouHeard: 'Correct — you heard',
    correctThatWas: 'Correct — that was',
    incorrectThisWas: 'This was',
    listenAndCompareWith: 'Listen again and compare it with',
    trainThisContrast: 'Train this contrast',
    trainContrast: 'Train',
    contrastDetails: 'Contrast details',
    viewContrastDetails: 'View contrast details',
    practiceExamples: 'Practice examples',
    availableNow: 'Available now',
    youChose: 'You chose',
    compareTheSounds: 'Compare the sounds',
    closeContrastDetails: 'Close contrast details',
  } as const;

export type TranslationSchema = Record<keyof typeof englishTranslations, string>;

export const alternateLanguages: Record<string, TranslationSchema> = {
  English: englishTranslations,
  日本語: {
    home: 'ホーム',
    results: '結果',
    info: '情報',
    settings: '設定',
    practicePairs: '練習',
    playAudio: '音声を再生',
    accuracyTrend: '最近の正答率の推移',
    timePracticed: '最近の練習時間',
    min: '分',
    weightedAverage: '加重平均',
    total: '合計',
    configureApp: 'アプリを設定',
    language: '言語',
    voiceSelection: '音声選択',
    systemDefault: 'システムデフォルト',
    loadingVoices: '音声を読み込み中...',
    noVoicesAvailable: '利用可能な音声がありません',
    refresh: '更新',
    appInfo: 'アプリ情報',
    version: 'バージョン',
    build: 'ビルド',
    usAccentFemale: '🇺🇸 米国アクセント（女性）',
    ukAccentMale: '🇬🇧 英国アクセント（男性）',
    americanEnglish: 'アメリカ英語',
    britishEnglish: 'イギリス英語',
    appearance: '外観',
    lightMode: 'ライトモード',
    darkMode: 'ダークモード',
    systemMode: 'システム設定',
    useEnglishUI: '英語表示を使用',
    englishUIDescription: 'インターフェースを英語で表示',
    titleOne: '耳を鍛えて、リスニング力を変えよう！',
    infoOne:
      '多くの英語学習者は "ship" と "sheep"、"light" と "right" の違いを聞き取れません。このアプリは、そうした違いを聞き取れる耳を作るためのトレーニングを提供します。',
    titleTwo: '目標',
    infoTwo:
      '各コントラストを60分以上練習することを目指しましょう。最初は難しく感じるかもしれませんが、練習を重ねることで脳が適応してきます！',
    titleThree: 'アプリの使い方',
    infoThree:
      '•「音声を再生」をタップして単語を聞く\n• 聞こえた単語を選択\n• 正解・不正解がすぐに表示\n• 練習履歴が保存され、進捗が確認できます',
    voicesAvailable: '利用可能な音声',
    voiceActive: '有効',
    theWordWas: 'その単語は',
    listenAgain: 'もう一度聞く',
    correct: '正解',
    incorrect: '不正解',
    placementTest: 'レベルテスト',
    retakePlacement: '次の練習セッションで再受験',
    skip: 'スキップ',
    todaySession: '今日のセッション',
    dailyGoal: '1日の目標',
    levelOf: 'レベル',
    mastered: 'マスター済み',
    levelUnlocked: 'レベルアップ！',
    levelCriteria: '速度を上げながら正解してレベルアップ。',
    pairsMastered: 'マスター済みコントラスト',
    levelsCompleted: '完了レベル',
    placementDescription: '開始レベルを決定',
    placementCompleted: '完了',
    placementResetConfirm: '練習タブに戻るとレベルテストが実行されます。',
    audioError: 'オーディオエラー',
    audioInitializing: 'オーディオシステムがまだ初期化中です。もう一度お試しください。',
    hr: '時間',
    helpTitle: '練習方法',
    helpBody: '単語を聞いて、聞こえた方をタップしてください。',
    helpTipPracticeTime: '各コントラストを約60分間練習しましょう',
    helpTipSpeedIncrease: 'レベルアップすると速度が上がります',
    helpTipFocusSounds: '音の違いを聞くことに集中しましょう',
    helpButton: 'わかりました',
    onboardingTitle: 'Soundwiseへようこそ',
    onboardingCTA: 'リスニングを始める',
    onboardingBullet1: '耳を鍛えよう。',
    onboardingBullet2: '単語を聞こう。',
    onboardingBullet3: '聞こえた単語を選ぼう。',
    onboardingBullet4: '練習は進捗に合わせて調整される。',
    onboardingBullet5: 'マイク不要。',
    practiceThisNext: '次はこれを練習',
    practiceThisNextReason: '最近の正答率がここで低めです。',
    practiceThisNextReasonNew: 'このコントラストはまだ練習していません。',
    practiceThisNextEmpty: 'いくつかのコントラストを練習すると、おすすめが表示されます。',
    noPairsFound: '対象のコントラストが見つかりません：',
    whichWordDidYouHear: 'どの単語が聞こえましたか？',
    compareTheTwoWords: '2つの単語を比べる',
    play: '再生',
    practicePair: '練習するペア',
    chooseAnotherExample: '別の例を選ぶ',
    loading: '読み込み中…',
    listenForSoundDifference: '音の違いに集中して聞いてください。',
    contrastMovedToLevel: 'このコントラストのレベルが上がりました：',
    tips: 'ヒント',
    closeHelp: 'ヘルプを閉じる',
    helpLabel: 'ヘルプ',
    doubleTapToSelectWord: 'ダブルタップしてこの単語を回答として選ぶ',
    doubleTapToHearAWord: 'ダブルタップして単語を聞く',
    doubleTapToHear: 'ダブルタップして聞く：',
    correctYouHeard: '正解。聞こえた音：',
    correctThatWas: '正解。その単語は',
    incorrectThisWas: 'この単語は',
    listenAndCompareWith: 'もう一度聞いて比べてみてください：',
    trainThisContrast: 'このコントラストを練習',
    trainContrast: '練習：',
    contrastDetails: 'コントラストの詳細',
    viewContrastDetails: 'コントラストの詳細を見る',
    practiceExamples: '練習例',
    availableNow: '現在利用可能',
    youChose: 'あなたの回答',
    compareTheSounds: '音を比べる',
    closeContrastDetails: 'コントラストの詳細を閉じる',
  },

  中文: {
    home: '首页',
    results: '结果',
    info: '信息',
    settings: '设置',
    practicePairs: '练习',
    playAudio: '播放音频',
    accuracyTrend: '最近准确率趋势',
    timePracticed: '最近练习时间',
    min: '分钟',
    weightedAverage: '加权平均',
    total: '总计',
    configureApp: '应用设置',
    language: '语言',
    voiceSelection: '语音选择',
    systemDefault: '系统默认',
    loadingVoices: '正在加载语音...',
    noVoicesAvailable: '没有可用的语音',
    refresh: '刷新',
    appInfo: '应用信息',
    version: '版本',
    build: '构建号',
    usAccentFemale: '🇺🇸 美国口音（女性）',
    ukAccentMale: '🇬🇧 英国口音（男性）',
    americanEnglish: '美式英语',
    britishEnglish: '英式英语',
    appearance: '外观',
    lightMode: '浅色模式',
    darkMode: '深色模式',
    systemMode: '系统设置',
    useEnglishUI: '使用英文界面',
    englishUIDescription: '以英文显示界面',
    titleOne: '训练你的耳朵，改善听力理解！',
    infoOne:
      '许多英语学习者分不清 "ship" 和 "sheep" 或 "light" 和 "right"。本应用帮助你训练听觉，分辨这些细微差别。',
    titleTwo: '目标',
    infoTwo: '每个对比音至少练习60分钟。起初可能很难，但练习多了，大脑会适应！',
    titleThree: '使用方法',
    infoThree:
      '• 点击“播放音频”听单词\n• 选择你听到的单词\n• 立即获得反馈\n• 记录练习进度，查看成长',
    voicesAvailable: '可用语音',
    voiceActive: '已启用',
    theWordWas: '那个词是',
    listenAgain: '再听一次',
    correct: '正确',
    incorrect: '不正确',
    placementTest: '水平测试',
    retakePlacement: '下次练习时重新测试',
    skip: '跳过',
    todaySession: '今日练习',
    dailyGoal: '每日目标',
    levelOf: '等级',
    mastered: '已掌握',
    levelUnlocked: '升级了！',
    levelCriteria: '在不断加快的速度下正确作答即可升级。',
    pairsMastered: '已掌握的对比音',
    levelsCompleted: '已完成等级',
    placementDescription: '确定你的起始等级',
    placementCompleted: '已完成',
    placementResetConfirm: '返回练习标签时将重新进行水平测试。',
    audioError: '音频错误',
    audioInitializing: '音频系统仍在初始化中，请稍后再试。',
    hr: '小时',
    helpTitle: '如何练习',
    helpBody: '听单词，然后点击你听到的。',
    helpTipPracticeTime: '每个对比音练习约60分钟',
    helpTipSpeedIncrease: '随着等级提升速度会加快',
    helpTipFocusSounds: '专注于听出声音的区别',
    helpButton: '知道了',
    onboardingTitle: '欢迎使用 Soundwise',
    onboardingCTA: '开始练习',
    onboardingBullet1: '训练你的听力。',
    onboardingBullet2: '仔细聆听单词。',
    onboardingBullet3: '选出你听到的单词。',
    onboardingBullet4: '练习根据你的进度自动调整。',
    onboardingBullet5: '无需麦克风。',
    practiceThisNext: '接下来练习这个',
    practiceThisNextReason: '你最近在这里的准确率较低。',
    practiceThisNextReasonNew: '你还没有练习过这个对比音。',
    practiceThisNextEmpty: '多练习几个对比音即可获得推荐。',
    noPairsFound: '找不到此分类的对比音：',
    whichWordDidYouHear: '你听到了哪个词？',
    compareTheTwoWords: '对比两个单词',
    play: '播放',
    practicePair: '练习词对',
    chooseAnotherExample: '选择其他示例',
    loading: '加载中…',
    listenForSoundDifference: '专心听声音的区别。',
    contrastMovedToLevel: '此对比音升至等级',
    tips: '小技巧',
    closeHelp: '关闭帮助',
    helpLabel: '帮助',
    doubleTapToSelectWord: '双击选择此词作为你的答案',
    doubleTapToHearAWord: '双击播放单词',
    doubleTapToHear: '双击收听',
    correctYouHeard: '正确。你听到了',
    correctThatWas: '正确。那个词是',
    incorrectThisWas: '这个词是',
    listenAndCompareWith: '再听一次，与之对比：',
    trainThisContrast: '练习此对比音',
    trainContrast: '练习',
    contrastDetails: '对比音详情',
    viewContrastDetails: '查看对比音详情',
    practiceExamples: '练习示例',
    availableNow: '当前可用',
    youChose: '你的选择',
    compareTheSounds: '对比声音',
    closeContrastDetails: '关闭对比音详情',
  },
  ภาษาไทย: {
    home: 'หน้าแรก',
    results: 'ผลลัพธ์',
    info: 'ข้อมูล',
    settings: 'การตั้งค่า',
    practicePairs: 'ฝึก',
    playAudio: 'เล่นเสียง',
    accuracyTrend: 'แนวโน้มความถูกต้องล่าสุด',
    timePracticed: 'เวลาฝึกฝนล่าสุด',
    min: 'นาที',
    weightedAverage: 'ค่าเฉลี่ยถ่วงน้ำหนัก',
    total: 'ทั้งหมด',
    configureApp: 'ตั้งค่าแอป',
    language: 'ภาษา',
    voiceSelection: 'เลือกเสียง',
    systemDefault: 'ค่าเริ่มต้นของระบบ',
    loadingVoices: 'กำลังโหลดเสียง...',
    noVoicesAvailable: 'ไม่มีเสียงที่ใช้ได้',
    refresh: 'รีเฟรช',
    appInfo: 'ข้อมูลแอป',
    version: 'เวอร์ชัน',
    build: 'บิลด์',
    usAccentFemale: '🇺🇸 สำเนียงอเมริกัน (ผู้หญิง)',
    ukAccentMale: '🇬🇧 สำเนียงอังกฤษ (ผู้ชาย)',
    americanEnglish: 'ภาษาอังกฤษอเมริกัน',
    britishEnglish: 'ภาษาอังกฤษแบบบริติช',
    appearance: 'รูปลักษณ์',
    lightMode: 'โหมดสว่าง',
    darkMode: 'โหมดมืด',
    systemMode: 'ตามระบบ',
    useEnglishUI: 'ใช้หน้าจอภาษาอังกฤษ',
    englishUIDescription: 'แสดงหน้าจอเป็นภาษาอังกฤษ',
    titleOne: 'ฝึกหูฟัง พัฒนาทักษะการฟัง!',
    infoOne:
      'ผู้เรียนภาษาอังกฤษหลายคนแยกไม่ออกระหว่างคำว่า "ship" กับ "sheep" หรือ "light" กับ "right" แอปนี้ช่วยฝึกให้คุณได้ยินความแตกต่างนั้น',
    titleTwo: 'เป้าหมาย',
    infoTwo:
      'ฝึกแต่ละเสียงให้ครบอย่างน้อย 60 นาที ไม่ต้องกังวลถ้ายังยากในตอนแรก สมองจะค่อยๆ ปรับตัว',
    titleThree: 'วิธีใช้งาน',
    infoThree:
      '• แตะ “เล่นเสียง” เพื่อฟัง\n• เลือกคำที่คุณได้ยิน\n• รับคำตอบถูก/ผิดทันที\n• ติดตามความก้าวหน้าของคุณ',    voicesAvailable: 'เสียงที่ใช้ได้',
    voiceActive: 'ใช้งาน',
    theWordWas: 'คำนั้นคือ',
    listenAgain: 'ฟังอีกครั้ง',
    correct: 'ถูกต้อง',
    incorrect: 'ไม่ถูกต้อง',
    placementTest: 'แบบทดสอบจัดระดับ',
    retakePlacement: 'ทำแบบทดสอบใหม่ในเซสชันถัดไป',
    skip: 'ข้าม',
    todaySession: 'เซสชันวันนี้',
    dailyGoal: 'เป้าหมายรายวัน',
    levelOf: 'ระดับ',
    mastered: 'เชี่ยวชาญแล้ว',
    levelUnlocked: 'เลื่อนระดับ!',
    levelCriteria: 'ตอบถูกที่ความเร็วเพิ่มขึ้นเพื่อเลื่อนระดับ',
    pairsMastered: 'เสียงที่เชี่ยวชาญ',
    levelsCompleted: 'ระดับที่สำเร็จ',
    placementDescription: 'กำหนดระดับเริ่มต้นของคุณ',
    placementCompleted: 'เสร็จสิ้น',
    placementResetConfirm: 'แบบทดสอบจัดระดับจะเริ่มเมื่อคุณกลับไปที่แท็บฝึกฝน',
    audioError: 'ข้อผิดพลาดเสียง',
    audioInitializing: 'ระบบเสียงกำลังเริ่มต้น กรุณาลองอีกครั้ง',
    hr: 'ชม.',
    helpTitle: 'วิธีฝึก',
    helpBody: 'ฟังคำแล้วแตะคำที่คุณได้ยิน',
    helpTipPracticeTime: 'ฝึกแต่ละเสียงประมาณ 60 นาที',
    helpTipSpeedIncrease: 'ความเร็วจะเพิ่มขึ้นเมื่อเลื่อนระดับ',
    helpTipFocusSounds: 'จดจ่อกับการฟังความแตกต่างของเสียง',
    helpButton: 'เข้าใจแล้ว',
    onboardingTitle: 'ยินดีต้อนรับสู่ Soundwise',
    onboardingCTA: 'เริ่มฟังเลย',
    onboardingBullet1: 'ฝึกหูฟังของคุณ',
    onboardingBullet2: 'ฟังคำที่ออกเสียง',
    onboardingBullet3: 'เลือกคำที่คุณได้ยิน',
    onboardingBullet4: 'การฝึกปรับตามความก้าวหน้าของคุณ',
    onboardingBullet5: 'ไม่ต้องใช้ไมโครโฟน',
    practiceThisNext: 'ฝึกคู่นี้ต่อไป',
    practiceThisNextReason: 'ความแม่นยำล่าสุดของคุณตรงนี้ต่ำกว่า',
    practiceThisNextReasonNew: 'คุณยังไม่ได้ฝึกเสียงนี้',
    practiceThisNextEmpty: 'ฝึกสักสองสามเสียงเพื่อรับคำแนะนำ',
    noPairsFound: 'ไม่พบเสียงในหมวดหมู่:',
    whichWordDidYouHear: 'คุณได้ยินคำไหน',
    compareTheTwoWords: 'เปรียบเทียบสองคำ',
    play: 'เล่น',
    practicePair: 'คู่คำที่ฝึก',
    chooseAnotherExample: 'เลือกตัวอย่างอื่น',
    loading: 'กำลังโหลด…',
    listenForSoundDifference: 'ฟังความแตกต่างของเสียง',
    contrastMovedToLevel: 'เสียงนี้เลื่อนไปอยู่ที่ระดับ',
    tips: 'เคล็ดลับ',
    closeHelp: 'ปิดวิธีใช้',
    helpLabel: 'วิธีใช้',
    doubleTapToSelectWord: 'แตะสองครั้งเพื่อเลือกคำนี้เป็นคำตอบ',
    doubleTapToHearAWord: 'แตะสองครั้งเพื่อฟังคำ',
    doubleTapToHear: 'แตะสองครั้งเพื่อฟัง',
    correctYouHeard: 'ถูก — คุณได้ยิน',
    correctThatWas: 'ถูก — คำนั้นคือ',
    incorrectThisWas: 'คำนั้นคือ',
    listenAndCompareWith: 'ฟังอีกครั้งและเปรียบเทียบกับ',
    trainThisContrast: 'ฝึกเสียงนี้',
    trainContrast: 'ฝึก',
    contrastDetails: 'รายละเอียดเสียงคู่ตรงข้าม',
    viewContrastDetails: 'ดูรายละเอียดเสียงคู่ตรงข้าม',
    practiceExamples: 'ตัวอย่างฝึก',
    availableNow: 'ใช้ได้ตอนนี้',
    youChose: 'คุณเลือก',
    compareTheSounds: 'เปรียบเทียบเสียง',
    closeContrastDetails: 'ปิดรายละเอียดเสียงคู่ตรงข้าม',
  },
  Español: {
    home: 'Inicio',
    results: 'Resultados',
    info: 'Información',
    settings: 'Configuración',
    practicePairs: 'Practicar',
    playAudio: 'Reproducir Audio',
    accuracyTrend: 'Tendencia de precisión reciente',
    timePracticed: 'Tiempo de práctica reciente',
    min: 'minutos',
    weightedAverage: 'Promedio ponderado',
    total: 'Total',
    configureApp: 'Configurar aplicación',
    language: 'Idioma',
    voiceSelection: 'Selección de voz',
    systemDefault: 'Predeterminado del sistema',
    loadingVoices: 'Cargando voces...',
    noVoicesAvailable: 'No hay voces disponibles',
    refresh: 'Actualizar',
    appInfo: 'Información de la aplicación',
    version: 'Versión',
    build: 'Compilación',
    usAccentFemale: '🇺🇸 Acento estadounidense (Mujer)',
    ukAccentMale: '🇬🇧 Acento británico (Hombre)',
    americanEnglish: 'Inglés americano',
    britishEnglish: 'Inglés británico',
    appearance: 'Apariencia',
    lightMode: 'Modo claro',
    darkMode: 'Modo oscuro',
    systemMode: 'Configuración del sistema',
    useEnglishUI: 'Usar interfaz en inglés',
    englishUIDescription: 'Mostrar interfaz en inglés',
    titleOne: '¡Entrena tus oídos y mejora tu comprensión auditiva!',
    infoOne:
      'Muchos estudiantes no distinguen "ship" de "sheep" o "light" de "right". Esta app te entrena para reconocer esas diferencias.',
    titleTwo: 'Meta',
    infoTwo:
      'Practica al menos 60 minutos por cada contraste. ¡Tu oído mejorará con el tiempo!',
    titleThree: 'Cómo funciona',
    infoThree:
      '• Toca "Reproducir Audio" para escuchar\n• Elige la palabra que crees haber oído\n• Recibe retroalimentación inmediata\n• Tu progreso se guarda automáticamente',
    voicesAvailable: 'voces disponibles',
    voiceActive: 'activas',
    theWordWas: 'La palabra era',
    listenAgain: 'Escuchar de nuevo',
    correct: 'Correcto',
    incorrect: 'Incorrecto',
    placementTest: 'Prueba de nivel',
    retakePlacement: 'Repetir en la próxima sesión',
    skip: 'Omitir',
    todaySession: 'Sesión de hoy',
    dailyGoal: 'Meta diaria',
    levelOf: 'Nivel',
    mastered: 'Dominado',
    levelUnlocked: '¡Subiste de nivel!',
    levelCriteria: 'Responde correctamente a velocidades crecientes para subir de nivel.',
    pairsMastered: 'Contrastes dominados',
    levelsCompleted: 'Niveles completados',
    placementDescription: 'Determina tu nivel inicial',
    placementCompleted: 'Completado',
    placementResetConfirm: 'La prueba de nivel se ejecutará cuando vuelvas a la pestaña de Práctica.',
    audioError: 'Error de audio',
    audioInitializing: 'El sistema de audio aún se está inicializando. Inténtelo de nuevo.',
    hr: 'h',
    helpTitle: 'Cómo practicar',
    helpBody: 'Escucha la palabra y toca lo que oigas.',
    helpTipPracticeTime: 'Practica cada contraste durante unos 60 minutos',
    helpTipSpeedIncrease: 'La velocidad aumenta al subir de nivel',
    helpTipFocusSounds: 'Concéntrate en escuchar la diferencia de sonido',
    helpButton: 'Entendido',
    onboardingTitle: 'Bienvenido a Soundwise',
    onboardingCTA: 'Empezar a escuchar',
    onboardingBullet1: 'Entrena tu oído.',
    onboardingBullet2: 'Escucha la palabra.',
    onboardingBullet3: 'Elige la palabra que escuchaste.',
    onboardingBullet4: 'La práctica se adapta a tu progreso.',
    onboardingBullet5: 'No necesitas micrófono.',
    practiceThisNext: 'Practica esto a continuación',
    practiceThisNextReason: 'Tu precisión reciente es más baja aquí.',
    practiceThisNextReasonNew: 'Aún no has practicado este contraste.',
    practiceThisNextEmpty: 'Practica algunos contrastes para obtener una recomendación.',
    noPairsFound: 'No se encontraron contrastes para',
    whichWordDidYouHear: '¿Qué palabra escuchaste?',
    compareTheTwoWords: 'Compara las dos palabras',
    play: 'Escuchar',
    practicePair: 'Par de práctica',
    chooseAnotherExample: 'Elegir otro ejemplo',
    loading: 'Cargando…',
    listenForSoundDifference: 'Escucha la diferencia de sonido.',
    contrastMovedToLevel: 'Este contraste pasó al nivel',
    tips: 'Consejos',
    closeHelp: 'Cerrar ayuda',
    helpLabel: 'Ayuda',
    doubleTapToSelectWord: 'Doble toque para seleccionar esta palabra como respuesta',
    doubleTapToHearAWord: 'Doble toque para escuchar una palabra',
    doubleTapToHear: 'Doble toque para escuchar',
    correctYouHeard: 'Correcto: escuchaste',
    correctThatWas: 'Correcto: era',
    incorrectThisWas: 'Era',
    listenAndCompareWith: 'Escucha de nuevo y compáralo con',
    trainThisContrast: 'Practicar este contraste',
    trainContrast: 'Practicar',
    contrastDetails: 'Detalles del contraste',
    viewContrastDetails: 'Ver detalles del contraste',
    practiceExamples: 'Ejemplos de práctica',
    availableNow: 'Disponible ahora',
    youChose: 'Elegiste',
    compareTheSounds: 'Compara los sonidos',
    closeContrastDetails: 'Cerrar detalles del contraste',
  },
  العربية: {
    home: 'الرئيسية',
    results: 'النتائج',
    info: 'المعلومات',
    settings: 'الإعدادات',
    practicePairs: 'تدرّب',
    playAudio: 'تشغيل الصوت',
    accuracyTrend: 'اتجاه الدقة الأخير',
    timePracticed: 'مدة التدريب الأخيرة',
    min: 'دقائق',
    weightedAverage: 'المتوسط المرجح',
    total: 'المجموع',
    configureApp: 'إعدادات التطبيق',
    language: 'اللغة',
    voiceSelection: 'اختيار الصوت',
    systemDefault: 'الافتراضي للنظام',
    loadingVoices: 'جارٍ تحميل الأصوات...',
    noVoicesAvailable: 'لا تتوفر أصوات',
    refresh: 'تحديث',
    appInfo: 'معلومات التطبيق',
    version: 'الإصدار',
    build: 'رقم البناء',
    usAccentFemale: '🇺🇸 لهجة أمريكية (أنثى)',
    ukAccentMale: '🇬🇧 لهجة بريطانية (ذكر)',
    americanEnglish: 'الإنجليزية الأمريكية',
    britishEnglish: 'الإنجليزية البريطانية',
    appearance: 'المظهر',
    lightMode: 'الوضع الفاتح',
    darkMode: 'الوضع الداكن',
    systemMode: 'إعداد النظام',
    useEnglishUI: 'استخدام الواجهة الإنجليزية',
    englishUIDescription: 'عرض الواجهة باللغة الإنجليزية',
    titleOne: 'درّب أذنيك وغيّر مهارات الاستماع!',
    infoOne:
      'الكثير من متعلمي اللغة الإنجليزية لا يميزون بين "ship" و "sheep" أو "light" و "right". هذا التطبيق يساعدك على تحسين تمييز هذه الأصوات.',
    titleTwo: 'الهدف',
    infoTwo:
      'خصص 60 دقيقة على الأقل لكل تباين صوتي. لا تقلق إذا بدا الأمر صعبًا في البداية — سيتكيف دماغك مع الوقت.',
    titleThree: 'طريقة الاستخدام',
    infoThree:
      '• اضغط على "تشغيل الصوت" للاستماع\n• اختر الكلمة التي سمعتها\n• ستحصل على نتيجة فورية\n• يتم حفظ تقدمك تلقائيًا',
    voicesAvailable: 'أصوات متاحة',
    voiceActive: 'نشط',
    theWordWas: 'الكلمة كانت',
    listenAgain: 'استمع مرة أخرى',
    correct: 'صحيح',
    incorrect: 'خطأ',
    placementTest: 'اختبار تحديد المستوى',
    retakePlacement: 'إعادة الاختبار في الجلسة القادمة',
    skip: 'تخطي',
    todaySession: 'جلسة اليوم',
    dailyGoal: 'الهدف اليومي',
    levelOf: 'المستوى',
    mastered: 'متقن',
    levelUnlocked: 'ترقية المستوى!',
    levelCriteria: 'أجب بشكل صحيح بسرعات متزايدة للترقية.',
    pairsMastered: 'التباينات المتقنة',
    levelsCompleted: 'المستويات المكتملة',
    placementDescription: 'حدد مستواك الابتدائي',
    placementCompleted: 'مكتمل',
    placementResetConfirm: 'سيبدأ اختبار تحديد المستوى عند العودة إلى تبويب التمرين.',
    audioError: 'خطأ في الصوت',
    audioInitializing: 'نظام الصوت لا يزال جارٍ تهيئته. يرجى المحاولة مجددًا.',
    hr: 'س',
    helpTitle: 'كيف تتدرب',
    helpBody: 'استمع إلى الكلمة ثم اضغط على ما سمعته.',
    helpTipPracticeTime: 'تدرّب على كل تباين لمدة 60 دقيقة تقريبًا',
    helpTipSpeedIncrease: 'تزداد السرعة كلما ارتقيت في المستوى',
    helpTipFocusSounds: 'ركّز على سماع الفرق بين الأصوات',
    helpButton: 'فهمت',
    onboardingTitle: 'مرحبًا بك في Soundwise',
    onboardingCTA: 'ابدأ الاستماع',
    onboardingBullet1: 'درّب أذنيك.',
    onboardingBullet2: 'استمع إلى الكلمة.',
    onboardingBullet3: 'اختر الكلمة التي سمعتها.',
    onboardingBullet4: 'تتكيف التدريبات مع تقدمك.',
    onboardingBullet5: 'لا حاجة لميكروفون.',
    practiceThisNext: 'تدرّب على هذا تاليًا',
    practiceThisNextReason: 'دقتك الأخيرة أقل هنا.',
    practiceThisNextReasonNew: 'لم تتدرّب على هذا التباين بعد.',
    practiceThisNextEmpty: 'تدرّب على بعض التباينات للحصول على توصية.',
    noPairsFound: 'لا توجد تباينات لـ',
    whichWordDidYouHear: 'أي كلمة سمعت؟',
    compareTheTwoWords: 'قارن بين الكلمتين',
    play: 'تشغيل',
    practicePair: 'زوج التدريب',
    chooseAnotherExample: 'اختر مثالاً آخر',
    loading: 'جارٍ التحميل…',
    listenForSoundDifference: 'استمع إلى الفرق في الصوت.',
    contrastMovedToLevel: 'انتقل هذا التباين إلى المستوى',
    tips: 'نصائح',
    closeHelp: 'إغلاق التعليمات',
    helpLabel: 'تعليمات',
    doubleTapToSelectWord: 'انقر مرتين لاختيار هذه الكلمة كإجابتك',
    doubleTapToHearAWord: 'انقر مرتين للاستماع إلى كلمة',
    doubleTapToHear: 'انقر مرتين للاستماع',
    correctYouHeard: 'صحيح — سمعت',
    correctThatWas: 'صحيح — الكلمة كانت',
    incorrectThisWas: 'الكلمة كانت',
    listenAndCompareWith: 'استمع مرة أخرى وقارنه مع',
    trainThisContrast: 'تدرّب على هذا التباين',
    trainContrast: 'تدرّب على',
    contrastDetails: 'تفاصيل التباين',
    viewContrastDetails: 'عرض تفاصيل التباين',
    practiceExamples: 'أمثلة للتدريب',
    availableNow: 'متاح الآن',
    youChose: 'اخترت',
    compareTheSounds: 'قارن بين الصوتين',
    closeContrastDetails: 'إغلاق تفاصيل التباين',
  },
  Русский: {
    home: 'Главная',
    results: 'Результаты',
    info: 'Информация',
    settings: 'Настройки',
    practicePairs: 'Практика',
    playAudio: 'Воспроизвести аудио',
    accuracyTrend: 'Недавняя тенденция точности',
    timePracticed: 'Недавнее время практики',
    min: 'мин',
    weightedAverage: 'Взвешенное среднее',
    total: 'Итого',
    configureApp: 'Настроить приложение',
    language: 'Язык',
    voiceSelection: 'Выбор голоса',
    systemDefault: 'По умолчанию',
    loadingVoices: 'Загрузка голосов...',
    noVoicesAvailable: 'Нет доступных голосов',
    refresh: 'Обновить',
    appInfo: 'Информация о приложении',
    version: 'Версия',
    build: 'Сборка',
    usAccentFemale: '🇺🇸 Американский акцент (Женский)',
    ukAccentMale: '🇬🇧 Британский акцент (Мужской)',
    americanEnglish: 'Американский английский',
    britishEnglish: 'Британский английский',
    appearance: 'Внешний вид',
    lightMode: 'Светлый режим',
    darkMode: 'Тёмный режим',
    systemMode: 'Настройки системы',
    useEnglishUI: 'Использовать английский интерфейс',
    englishUIDescription: 'Отображать интерфейс на английском',
    titleOne: 'Тренируй слух — улучшай понимание!',
    infoOne:
      'Многие изучающие английский не различают "ship" и "sheep" или "light" и "right". Это приложение поможет научиться их слышать.',
    titleTwo: 'Цель',
    infoTwo:
      'Практикуй каждый контраст минимум 60 минут. Сложно сначала — но мозг привыкнет!',
    titleThree: 'Как это работает',
    infoThree:
      '• Нажми “Воспроизвести аудио”\n• Выбери слово, которое услышал\n• Мгновенная обратная связь\n• Прогресс сохраняется',
    voicesAvailable: 'доступных голосов',
    voiceActive: 'активных',
    theWordWas: 'Слово было',
    listenAgain: 'Послушать снова',
    correct: 'Правильно',
    incorrect: 'Неправильно',
    placementTest: 'Тест на уровень',
    retakePlacement: 'Пройти заново в следующей сессии',
    skip: 'Пропустить',
    todaySession: 'Сегодняшняя сессия',
    dailyGoal: 'Дневная цель',
    levelOf: 'Уровень',
    mastered: 'Освоено',
    levelUnlocked: 'Уровень повышен!',
    levelCriteria: 'Отвечайте правильно на возрастающей скорости для повышения уровня.',
    pairsMastered: 'Освоено контрастов',
    levelsCompleted: 'Завершено уровней',
    placementDescription: 'Определите начальный уровень',
    placementCompleted: 'Завершено',
    placementResetConfirm: 'Тест на уровень запустится при возвращении на вкладку Практика.',
    audioError: 'Ошибка аудио',
    audioInitializing: 'Аудиосистема ещё инициализируется. Попробуйте снова.',
    hr: 'ч',
    helpTitle: 'Как практиковаться',
    helpBody: 'Прослушайте слово и нажмите на то, что услышали.',
    helpTipPracticeTime: 'Практикуйте каждый контраст около 60 минут',
    helpTipSpeedIncrease: 'Скорость увеличивается с повышением уровня',
    helpTipFocusSounds: 'Сосредоточьтесь на различии звуков',
    helpButton: 'Понятно',
    onboardingTitle: 'Добро пожаловать в Soundwise',
    onboardingCTA: 'Начать слушать',
    onboardingBullet1: 'Тренируй слух.',
    onboardingBullet2: 'Слушай слово.',
    onboardingBullet3: 'Выбери услышанное слово.',
    onboardingBullet4: 'Упражнения подстраиваются под твой прогресс.',
    onboardingBullet5: 'Микрофон не нужен.',
    practiceThisNext: 'Дальше практикуйте это',
    practiceThisNextReason: 'Здесь ваша недавняя точность ниже.',
    practiceThisNextReasonNew: 'Вы ещё не практиковали этот контраст.',
    practiceThisNextEmpty: 'Попрактикуйте несколько контрастов, чтобы получить рекомендацию.',
    noPairsFound: 'Контрасты не найдены для',
    whichWordDidYouHear: 'Какое слово вы услышали?',
    compareTheTwoWords: 'Сравните два слова',
    play: 'Слушать',
    practicePair: 'Тренировочная пара',
    chooseAnotherExample: 'Выбрать другой пример',
    loading: 'Загрузка…',
    listenForSoundDifference: 'Слушайте, улавливая разницу в звуках.',
    contrastMovedToLevel: 'Этот контраст перешёл на уровень',
    tips: 'Советы',
    closeHelp: 'Закрыть справку',
    helpLabel: 'Справка',
    doubleTapToSelectWord: 'Дважды нажмите, чтобы выбрать это слово в качестве ответа',
    doubleTapToHearAWord: 'Дважды нажмите, чтобы услышать слово',
    doubleTapToHear: 'Дважды нажмите, чтобы услышать',
    correctYouHeard: 'Правильно — вы услышали',
    correctThatWas: 'Правильно — это было',
    incorrectThisWas: 'Это было',
    listenAndCompareWith: 'Послушайте ещё раз и сравните с',
    trainThisContrast: 'Тренировать этот контраст',
    trainContrast: 'Тренировать',
    contrastDetails: 'Подробности контраста',
    viewContrastDetails: 'Посмотреть подробности контраста',
    practiceExamples: 'Примеры для практики',
    availableNow: 'Доступно сейчас',
    youChose: 'Вы выбрали',
    compareTheSounds: 'Сравните звуки',
    closeContrastDetails: 'Закрыть подробности контраста',
  },
  한국어: {
    home: '홈',
    results: '결과',
    info: '정보',
    settings: '설정',
    practicePairs: '연습',
    playAudio: '오디오 재생',
    accuracyTrend: '최근 정확도 추이',
    timePracticed: '최근 연습 시간',
    min: '분',
    weightedAverage: '가중 평균',
    total: '총합',
    configureApp: '앱 설정',
    language: '언어',
    voiceSelection: '음성 선택',
    systemDefault: '시스템 기본값',
    loadingVoices: '음성 로딩 중...',
    noVoicesAvailable: '사용 가능한 음성이 없습니다',
    refresh: '새로고침',
    appInfo: '앱 정보',
    version: '버전',
    build: '빌드',
    usAccentFemale: '🇺🇸 미국 악센트 (여성)',
    ukAccentMale: '🇬🇧 영국 악센트 (남성)',
    americanEnglish: '미국 영어',
    britishEnglish: '영국 영어',
    appearance: '외관',
    lightMode: '라이트 모드',
    darkMode: '다크 모드',
    systemMode: '시스템 설정',
    useEnglishUI: '영어 UI 사용',
    englishUIDescription: '인터페이스를 영어로 표시',
    titleOne: '귀를 훈련하여 듣기 능력을 향상시키세요!',
    infoOne:
      '많은 영어 학습자들이 "ship"과 "sheep", "light"과 "right"의 차이를 구별하지 못합니다. 이 앱은 그런 구별을 가능하게 도와줍니다.',
    titleTwo: '목표',
    infoTwo:
      '각 대비음을 최소 60분 이상 연습하세요. 처음에는 어려워도 점점 더 잘 들릴 거예요!',
    titleThree: '사용 방법',
    infoThree:
      '• "오디오 재생"을 눌러 단어 듣기\n• 들은 단어 선택하기\n• 즉시 피드백 받기\n• 진행 상황 자동 저장',
    voicesAvailable: '사용 가능한 음성',
    voiceActive: '활성',
    theWordWas: '그 단어는',
    listenAgain: '다시 듣기',
    correct: '정답',
    incorrect: '오답',
    placementTest: '배치 테스트',
    retakePlacement: '다음 연습 세션에서 다시 테스트',
    skip: '건너뛰기',
    todaySession: '오늘의 세션',
    dailyGoal: '일일 목표',
    levelOf: '레벨',
    mastered: '마스터 완료',
    levelUnlocked: '레벨 업!',
    levelCriteria: '속도를 높여가며 정답을 맞추면 레벨업합니다.',
    pairsMastered: '마스터한 대비음',
    levelsCompleted: '완료된 레벨',
    placementDescription: '시작 레벨을 결정하세요',
    placementCompleted: '완료',
    placementResetConfirm: '연습 탭으로 돌아가면 배치 테스트가 실행됩니다.',
    audioError: '오디오 오류',
    audioInitializing: '오디오 시스템이 아직 초기화 중입니다. 다시 시도해 주세요.',
    hr: '시간',
    helpTitle: '연습 방법',
    helpBody: '단어를 듣고 들린 것을 탭하세요.',
    helpTipPracticeTime: '각 대비음을 약 60분 동안 연습하세요',
    helpTipSpeedIncrease: '레벨이 올라가면 속도가 빨라집니다',
    helpTipFocusSounds: '소리 차이를 듣는 데 집중하세요',
    helpButton: '알겠습니다',
    onboardingTitle: 'Soundwise에 오신 것을 환영합니다',
    onboardingCTA: '듣기 시작하기',
    onboardingBullet1: '귀를 훈련하세요.',
    onboardingBullet2: '단어를 들어보세요.',
    onboardingBullet3: '들은 단어를 선택하세요.',
    onboardingBullet4: '연습은 나의 진행 상황에 맞게 조정됩니다.',
    onboardingBullet5: '마이크가 필요 없습니다.',
    practiceThisNext: '다음은 이걸 연습하세요',
    practiceThisNextReason: '최근 정확도가 여기서 더 낮습니다.',
    practiceThisNextReasonNew: '이 대비음은 아직 연습하지 않았습니다.',
    practiceThisNextEmpty: '몇 개의 대비음을 연습하면 추천을 받을 수 있습니다.',
    noPairsFound: '대비음을 찾을 수 없습니다:',
    whichWordDidYouHear: '어떤 단어를 들었나요?',
    compareTheTwoWords: '두 단어 비교하기',
    play: '재생',
    practicePair: '연습 단어 쌍',
    chooseAnotherExample: '다른 예시 선택하기',
    loading: '불러오는 중…',
    listenForSoundDifference: '소리 차이를 들어보세요.',
    contrastMovedToLevel: '이 대비음이 레벨로 올랐습니다:',
    tips: '도움말',
    closeHelp: '도움말 닫기',
    helpLabel: '도움말',
    doubleTapToSelectWord: '두 번 탭해서 이 단어를 답으로 선택하기',
    doubleTapToHearAWord: '두 번 탭해서 단어 듣기',
    doubleTapToHear: '두 번 탭해서 듣기:',
    correctYouHeard: '정답 — 들린 소리:',
    correctThatWas: '정답 — 그 단어는',
    incorrectThisWas: '이 단어는',
    listenAndCompareWith: '다시 듣고 비교해보세요:',
    trainThisContrast: '이 대비음 훈련하기',
    trainContrast: '훈련:',
    contrastDetails: '대비음 상세 정보',
    viewContrastDetails: '대비음 상세 정보 보기',
    practiceExamples: '연습 예시',
    availableNow: '지금 사용 가능',
    youChose: '선택한 단어',
    compareTheSounds: '소리 비교하기',
    closeContrastDetails: '대비음 상세 정보 닫기',
  },
  'हिन्दी / اردو': {
    home: 'होम/ہوم',
    results: 'परिणाम/نتائج',
    info: 'जानकारी/معلومات',
    settings: 'सेटिंग्स/ترتیبات',
    practicePairs: 'अभ्यास/مشق',
    playAudio: 'ऑडियो चलाएँ/آڈیو چلائیں',
    accuracyTrend: 'हाल की सटीकता प्रवृत्ति/حالیہ درستگی کا رجحان',
    timePracticed: 'हाल का अभ्यास समय/حالیہ مشق کا وقت',
    min: 'मिनट/منٹ',
    weightedAverage: 'भारित औसत/وزنی اوسط',
    total: 'कुल/کل',
    configureApp: 'ऐप सेटिंग्स/ایپ ترتیبات',
    language: 'भाषा/زبان',
    voiceSelection: 'आवाज़ चयन/آواز کا انتخاب',
    systemDefault: 'सिस्टम डिफ़ॉल्ट/سسٹم ڈیفالٹ',
    loadingVoices: 'आवाज़ें लोड हो रही हैं.../آوازیں لوڈ ہو رہی ہیں...',
    noVoicesAvailable: 'कोई आवाज़ उपलब्ध नहीं/کوئی آواز دستیاب نہیں',
    refresh: 'रीफ़्रेश/ریفریش',
    appInfo: 'ऐप जानकारी/ایپ کی معلومات',
    version: 'संस्करण/ورژن',
    build: 'बिल्ड/بلڈ',
    usAccentFemale: '🇺🇸 अमेरिकी उच्चारण (महिला)/امریکی لہجہ (خاتون)',
    ukAccentMale: '🇬🇧 ब्रिटिश उच्चारण (पुरुष)/برطانوی لہجہ (مرد)',
    americanEnglish: 'अमेरिकी अंग्रेज़ी/امریکی انگریزی',
    britishEnglish: 'ब्रिटिश अंग्रेज़ी/برطانوی انگریزی',
    appearance: 'दिखावट/ظہور',
    lightMode: 'लाइट मोड/لائٹ موڈ',
    darkMode: 'डार्क मोड/ڈارک موڈ',
    systemMode: 'सिस्टम सेटिंग/سسٹم کی ترتیب',
    useEnglishUI: 'अंग्रेज़ी UI उपयोग करें/انگریزی UI استعمال کریں',
    englishUIDescription: 'इंटरफ़ेस अंग्रेज़ी में दिखाएं/انٹرفیس انگریزی میں دکھائیں',
    titleOne: 'अपने कानों को प्रशिक्षित करें, सुनने की क्षमता सुधारें!/!اپنے کانوں کو تربیت دیں، سننے کی صلاحیت بہتر بنائیں',
    infoOne:
      '"ship" और "sheep" या "light" और "right" जैसे शब्दों में फर्क करना कठिन हो सकता है। यह ऐप आपको वह फर्क सुनने में मदद करता है।/"ship" اور "sheep" یا "light" اور "right" جیسے الفاظ میں فرق کرنا مشکل ہو سکتا ہے۔ یہ ایپ آپ کو یہ فرق سننے میں مدد کرتی ہے۔',
    titleTwo: 'लक्ष्य/ہدف',
    infoTwo:
      'हर ध्वनि अंतर पर कम से कम 60 मिनट अभ्यास करें। शुरुआत में कठिन लग सकता है, लेकिन अभ्यास से सुधार होगा!/ہر آواز کے فرق پر کم از کم 60 منٹ مشق کریں۔ شروع میں مشکل لگ سکتا ہے، لیکن مشق سے بہتری آئے گی!',
    titleThree: 'यह कैसे काम करता है/یہ کیسے کام کرتا ہے',
    infoThree:
      '• "ऑडियो चलाएँ" पर टैप करें\n• सुनी हुई शब्द चुनें\n• तुरंत प्रतिक्रिया पाएं\n• आपकी प्रगति सहेजी जाती है/• "آڈیو چلائیں" پر ٹیپ کریں\n• سنا ہوا لفظ چنیں\n• فوری ردعمل حاصل کریں\n• آپ کی پیشرفت خود بخود محفوظ ہوتی ہے',
    voicesAvailable: 'उपलब्ध आवाज़ें',
    voiceActive: 'सक्रिय/فعال',
    theWordWas: 'वह शब्द था',
    listenAgain: 'फिर से सुनें',
    correct: 'सही',
    incorrect: 'गलत',
    placementTest: 'प्लेसमेंट टेस्ट',
    retakePlacement: 'अगले सत्र में फिर से लें',
    skip: 'छोड़ें',
    todaySession: 'आज का सत्र',
    dailyGoal: 'दैनिक लक्ष्य',
    levelOf: 'स्तर',
    mastered: 'महारत हासिल',
    levelUnlocked: 'स्तर बढ़ा!',
    levelCriteria: 'बढ़ती गति पर सही उत्तर देकर स्तर बढ़ाएं।/بڑھتی رفتار میں صحیح جواب دے کر سطح بڑھائیں۔',
    pairsMastered: 'महारत हासिल ध्वनि अंतर/مہارت حاصل آوازیں',
    levelsCompleted: 'पूर्ण स्तर/مکمل سطح',
    placementDescription: 'अपना शुरुआती स्तर तय करें/اپنی ابتدائی سطح طے کریں',
    placementCompleted: 'पूर्ण/مکمل',
    placementResetConfirm: 'अभ्यास टैब पर लौटने पर प्लेसमेंट टेस्ट चलेगा।/مشق ٹیب پر واپس آنے پر ٹیسٹ شروع ہوگا۔',
    audioError: 'ऑडियो त्रुटि/آڈیو نقص',
    audioInitializing: 'ऑडियो सिस्टम अभी शुरू हो रहा है। कृपया पुनः प्रयास करें।/آڈیو سسٹم ابھی شروع ہو رہا ہے۔ دوبارہ کوشش کریں۔',
    hr: 'घंटे/گھنٹے',
    helpTitle: 'अभ्यास कैसे करें/مشق کیسے کریں',
    helpBody: 'शब्द सुनें और जो सुना उसे टैप करें।/لفظ سنیں اور جو سنا اسے ٹیپ کریں۔',
    helpTipPracticeTime: 'प्रत्येक ध्वनि अंतर को लगभग 60 मिनट तक अभ्यास करें/ہر آواز کے فرق کو تقریباً 60 منٹ مشق کریں',
    helpTipSpeedIncrease: 'स्तर बढ़ने पर गति बढ़ती है/سطح بڑھنے پر رفتار بڑھتی ہے',
    helpTipFocusSounds: 'ध्वनि के अंतर को सुनने पर ध्यान दें/آواز کے فرق کو سننے پر توجہ دیں',
    helpButton: 'समझ गया/سمجھ گیا',
    onboardingTitle: 'Soundwise में आपका स्वागत है/Soundwise میں خوش آمدید',
    onboardingCTA: 'सुनना शुरू करें/سننا شروع کریں',
    onboardingBullet1: 'अपने कान को प्रशिक्षित करें।/اپنے کانوں کو تربیت دیں۔',
    onboardingBullet2: 'शब्द को ध्यान से सुनें।/لفظ کو غور سے سنیں۔',
    onboardingBullet3: 'जो शब्द सुना वो चुनें।/جو لفظ سنا وہ چنیں۔',
    onboardingBullet4: 'अभ्यास आपकी प्रगति के अनुसार बदलता है।/مشق آپ کی پیشرفت کے مطابق ڈھلتی ہے۔',
    onboardingBullet5: 'माइक की ज़रूरत नहीं।/مائیک کی ضرورت نہیں۔',
    practiceThisNext: 'आगे इसका अभ्यास करें/اگلی مشق یہی کریں',
    practiceThisNextReason: 'यहाँ आपकी हाल की सटीकता कम है।/یہاں آپ کی حالیہ درستگی کم ہے۔',
    practiceThisNextReasonNew: 'आपने अभी तक इस ध्वनि अंतर का अभ्यास नहीं किया है।/آپ نے ابھی تک یہ آوازی فرق مشق نہیں کیا۔',
    practiceThisNextEmpty: 'कुछ ध्वनि अंतरों का अभ्यास करें ताकि सुझाव मिल सके।/کچھ آوازی فرقوں کی مشق کریں تاکہ تجویز مل سکے۔',
    noPairsFound: 'इस श्रेणी में कोई ध्वनि अंतर नहीं मिला:/اس زمرے میں کوئی آوازی فرق نہیں ملا:',
    whichWordDidYouHear: 'आपने कौन सा शब्द सुना?/آپ نے کون سا لفظ سنا؟',
    compareTheTwoWords: 'दो शब्दों की तुलना करें/دو الفاظ کا موازنہ کریں',
    play: 'सुनें/سنیں',
    practicePair: 'अभ्यास जोड़ी/مشق کا جوڑا',
    chooseAnotherExample: 'दूसरा उदाहरण चुनें/دوسری مثال منتخب کریں',
    loading: 'लोड हो रहा है…/لوڈ ہو رہا ہے…',
    listenForSoundDifference: 'ध्वनि का अंतर सुनें।/آواز کا فرق سنیں۔',
    contrastMovedToLevel: 'यह ध्वनि अंतर स्तर पर पहुँचा/یہ آوازی فرق سطح پر پہنچا',
    tips: 'सुझाव/تجاویز',
    closeHelp: 'सहायता बंद करें/مدد بند کریں',
    helpLabel: 'सहायता/مدد',
    doubleTapToSelectWord: 'इस शब्द को अपना उत्तर चुनने के लिए दो बार टैप करें/اس لفظ کو اپنا جواب چننے کے لیے دو بار ٹیپ کریں',
    doubleTapToHearAWord: 'शब्द सुनने के लिए दो बार टैप करें/لفظ سننے کے لیے دو بار ٹیپ کریں',
    doubleTapToHear: 'सुनने के लिए दो बार टैप करें/سننے کے لیے دو بار ٹیپ کریں',
    correctYouHeard: 'सही — आपने सुना/صحیح — آپ نے سنا',
    correctThatWas: 'सही — वह शब्द था/صحیح — وہ لفظ تھا',
    incorrectThisWas: 'यह शब्द था/یہ لفظ تھا',
    listenAndCompareWith: 'फिर से सुनें और इससे तुलना करें:/دوبارہ سنیں اور اس سے موازنہ کریں:',
    trainThisContrast: 'यह ध्वनि अंतर सीखें/یہ آوازی فرق سیکھیں',
    trainContrast: 'सीखें/سیکھیں',
    contrastDetails: 'ध्वनि अंतर का विवरण/آوازی فرق کی تفصیل',
    viewContrastDetails: 'ध्वनि अंतर का विवरण देखें/آوازی فرق کی تفصیل دیکھیں',
    practiceExamples: 'अभ्यास के उदाहरण/مشق کی مثالیں',
    availableNow: 'अभी उपलब्ध/ابھی دستیاب',
    youChose: 'आपने चुना/آپ نے چنا',
    compareTheSounds: 'ध्वनियों की तुलना करें/آوازوں کا موازنہ کریں',
    closeContrastDetails: 'ध्वनि अंतर का विवरण बंद करें/آوازی فرق کی تفصیل بند کریں',
  },
  Português: {
    home: 'Início',
    results: 'Resultados',
    info: 'Informações',
    settings: 'Configurações',
    practicePairs: 'Praticar',
    playAudio: 'Reproduzir áudio',
    accuracyTrend: 'Tendência de precisão recente',
    timePracticed: 'Tempo de prática recente',
    min: 'minutos',
    weightedAverage: 'Média ponderada',
    total: 'Total',
    configureApp: 'Configurar aplicativo',
    language: 'Idioma',
    voiceSelection: 'Seleção de voz',
    systemDefault: 'Padrão do sistema',
    loadingVoices: 'Carregando vozes...',
    noVoicesAvailable: 'Nenhuma voz disponível',
    refresh: 'Atualizar',
    appInfo: 'Informações do aplicativo',
    version: 'Versão',
    build: 'Compilação',
    usAccentFemale: '🇺🇸 Sotaque americano (Feminino)',
    ukAccentMale: '🇬🇧 Sotaque britânico (Masculino)',
    americanEnglish: 'Inglês americano',
    britishEnglish: 'Inglês britânico',
    appearance: 'Aparência',
    lightMode: 'Modo claro',
    darkMode: 'Modo escuro',
    systemMode: 'Configuração do sistema',
    useEnglishUI: 'Usar interface em inglês',
    englishUIDescription: 'Exibir interface em inglês',
    titleOne: 'Treine seus ouvidos, melhore sua escuta!',
    infoOne:
      'Muitos alunos de inglês não distinguem "ship" de "sheep" ou "light" de "right". Este app ajuda a treinar sua audição para perceber essas diferenças.',
    titleTwo: 'Objetivo',
    infoTwo:
      'Pratique pelo menos 60 minutos com cada contraste. No início pode ser difícil, mas seu cérebro vai se adaptar!',
    titleThree: 'Como funciona',
    infoThree:
      '• Toque em "Reproduzir áudio" para ouvir\n• Escolha a palavra que você ouviu\n• Receba feedback imediato\n• Acompanhe seu progresso automaticamente',
    voicesAvailable: 'vozes disponíveis',
    voiceActive: 'ativas',
    theWordWas: 'A palavra era',
    listenAgain: 'Ouvir novamente',
    correct: 'Correto',
    incorrect: 'Incorreto',
    placementTest: 'Teste de nível',
    retakePlacement: 'Refazer na próxima sessão',
    skip: 'Pular',
    todaySession: 'Sessão de hoje',
    dailyGoal: 'Meta diária',
    levelOf: 'Nível',
    mastered: 'Dominado',
    levelUnlocked: 'Subiu de nível!',
    levelCriteria: 'Acerte em velocidades crescentes para subir de nível.',
    pairsMastered: 'Contrastes dominados',
    levelsCompleted: 'Níveis completados',
    placementDescription: 'Determine seu nível inicial',
    placementCompleted: 'Concluído',
    placementResetConfirm: 'O teste de nível será executado quando você voltar à aba Prática.',
    audioError: 'Erro de áudio',
    audioInitializing: 'O sistema de áudio ainda está inicializando. Tente novamente.',
    hr: 'h',
    helpTitle: 'Como praticar',
    helpBody: 'Ouça a palavra e toque no que você ouviu.',
    helpTipPracticeTime: 'Pratique cada contraste por cerca de 60 minutos',
    helpTipSpeedIncrease: 'A velocidade aumenta conforme você sobe de nível',
    helpTipFocusSounds: 'Concentre-se em ouvir a diferença dos sons',
    helpButton: 'Entendi',
    onboardingTitle: 'Bem-vindo ao Soundwise',
    onboardingCTA: 'Começar a ouvir',
    onboardingBullet1: 'Treine seu ouvido.',
    onboardingBullet2: 'Ouça a palavra.',
    onboardingBullet3: 'Escolha a palavra que você ouviu.',
    onboardingBullet4: 'A prática se adapta ao seu progresso.',
    onboardingBullet5: 'Não precisa de microfone.',
    practiceThisNext: 'Pratique isto a seguir',
    practiceThisNextReason: 'Sua precisão recente é menor aqui.',
    practiceThisNextReasonNew: 'Você ainda não praticou este contraste.',
    practiceThisNextEmpty: 'Pratique alguns contrastes para receber uma recomendação.',
    noPairsFound: 'Nenhum contraste encontrado para',
    whichWordDidYouHear: 'Qual palavra você ouviu?',
    compareTheTwoWords: 'Comparar as duas palavras',
    play: 'Ouvir',
    practicePair: 'Par de prática',
    chooseAnotherExample: 'Escolher outro exemplo',
    loading: 'Carregando…',
    listenForSoundDifference: 'Ouça a diferença no som.',
    contrastMovedToLevel: 'Este contraste avançou para o nível',
    tips: 'Dicas',
    closeHelp: 'Fechar ajuda',
    helpLabel: 'Ajuda',
    doubleTapToSelectWord: 'Toque duas vezes para selecionar esta palavra como resposta',
    doubleTapToHearAWord: 'Toque duas vezes para ouvir uma palavra',
    doubleTapToHear: 'Toque duas vezes para ouvir',
    correctYouHeard: 'Correto — você ouviu',
    correctThatWas: 'Correto — era',
    incorrectThisWas: 'Era',
    listenAndCompareWith: 'Ouça novamente e compare com',
    trainThisContrast: 'Praticar este contraste',
    trainContrast: 'Praticar',
    contrastDetails: 'Detalhes do contraste',
    viewContrastDetails: 'Ver detalhes do contraste',
    practiceExamples: 'Exemplos de prática',
    availableNow: 'Disponível agora',
    youChose: 'Você escolheu',
    compareTheSounds: 'Compare os sons',
    closeContrastDetails: 'Fechar detalhes do contraste',
  },
  'Tiếng Việt': {
    home: 'Trang chủ',
    results: 'Kết quả',
    info: 'Thông tin',
    settings: 'Cài đặt',
    practicePairs: 'Luyện tập',
    playAudio: 'Phát âm thanh',
    accuracyTrend: 'Xu hướng độ chính xác gần đây',
    timePracticed: 'Thời gian luyện tập gần đây',
    min: 'phút',
    weightedAverage: 'Trung bình trọng số',
    total: 'Tổng cộng',
    configureApp: 'Thiết lập ứng dụng',
    language: 'Ngôn ngữ',
    voiceSelection: 'Chọn giọng nói',
    systemDefault: 'Mặc định hệ thống',
    loadingVoices: 'Đang tải giọng nói...',
    noVoicesAvailable: 'Không có giọng nói nào',
    refresh: 'Làm mới',
    appInfo: 'Thông tin ứng dụng',
    version: 'Phiên bản',
    build: 'Bản build',
    usAccentFemale: '🇺🇸 Giọng Mỹ (Nữ)',
    ukAccentMale: '🇬🇧 Giọng Anh (Nam)',
    americanEnglish: 'Tiếng Anh Mỹ',
    britishEnglish: 'Tiếng Anh Anh Quốc',
    appearance: 'Giao diện',
    lightMode: 'Chế độ sáng',
    darkMode: 'Chế độ tối',
    systemMode: 'Cài đặt hệ thống',
    useEnglishUI: 'Sử dụng giao diện tiếng Anh',
    englishUIDescription: 'Hiển thị giao diện bằng tiếng Anh',
    titleOne: 'Luyện tai, cải thiện kỹ năng nghe!',
    infoOne:
      'Nhiều người học tiếng Anh không phân biệt được "ship" và "sheep", hoặc "light" và "right". Ứng dụng này giúp bạn luyện nghe các âm thanh khó phân biệt.',
    titleTwo: 'Mục tiêu',
    infoTwo:
      'Dành ít nhất 60 phút luyện tập mỗi cặp âm. Ban đầu có thể khó, nhưng não bạn sẽ thích nghi dần!',
    titleThree: 'Cách sử dụng',
    infoThree:
      '• Nhấn "Phát âm thanh" để nghe\n• Chọn từ bạn nghe thấy\n• Nhận phản hồi ngay lập tức\n• Tiến độ luyện tập sẽ được lưu lại',
    voicesAvailable: 'giọng có sẵn',
    voiceActive: 'đang dùng',
    theWordWas: 'Từ đó là',
    listenAgain: 'Nghe lại',
    correct: 'Đúng',
    incorrect: 'Sai',
    placementTest: 'Bài kiểm tra xếp lớp',
    retakePlacement: 'Làm lại ở phiên tiếp theo',
    skip: 'Bỏ qua',
    todaySession: 'Phiên hôm nay',
    dailyGoal: 'Mục tiêu hàng ngày',
    levelOf: 'Cấp',
    mastered: 'Thành thạo',
    levelUnlocked: 'Lên cấp!',
    levelCriteria: 'Trả lời đúng ở tốc độ tăng dần để lên cấp.',
    pairsMastered: 'Cặp âm đã thành thạo',
    levelsCompleted: 'Cấp đã hoàn thành',
    placementDescription: 'Xác định cấp bắt đầu của bạn',
    placementCompleted: 'Hoàn tất',
    placementResetConfirm: 'Bài kiểm tra xếp lớp sẽ chạy khi bạn quay lại tab Luyện tập.',
    audioError: 'Lỗi âm thanh',
    audioInitializing: 'Hệ thống âm thanh vẫn đang khởi tạo. Vui lòng thử lại.',
    hr: 'giờ',
    helpTitle: 'Cách luyện tập',
    helpBody: 'Nghe từ và nhấn vào từ bạn nghe được.',
    helpTipPracticeTime: 'Luyện tập mỗi cặp âm khoảng 60 phút',
    helpTipSpeedIncrease: 'Tốc độ tăng khi bạn lên cấp',
    helpTipFocusSounds: 'Tập trung nghe sự khác biệt của âm thanh',
    helpButton: 'Đã hiểu',
    onboardingTitle: 'Chào mừng đến với Soundwise',
    onboardingCTA: 'Bắt đầu luyện nghe',
    onboardingBullet1: 'Luyện tai nghe của bạn.',
    onboardingBullet2: 'Nghe từ được phát.',
    onboardingBullet3: 'Chọn từ bạn vừa nghe.',
    onboardingBullet4: 'Bài tập tự điều chỉnh theo tiến độ của bạn.',
    onboardingBullet5: 'Không cần dùng micro.',
    practiceThisNext: 'Luyện cặp này tiếp theo',
    practiceThisNextReason: 'Độ chính xác gần đây của bạn ở đây thấp hơn.',
    practiceThisNextReasonNew: 'Bạn chưa luyện tập cặp âm này.',
    practiceThisNextEmpty: 'Hãy luyện vài cặp âm để nhận gợi ý.',
    noPairsFound: 'Không tìm thấy cặp âm cho',
    whichWordDidYouHear: 'Bạn nghe thấy từ nào?',
    compareTheTwoWords: 'So sánh hai từ',
    play: 'Nghe',
    practicePair: 'Cặp từ luyện tập',
    chooseAnotherExample: 'Chọn ví dụ khác',
    loading: 'Đang tải…',
    listenForSoundDifference: 'Lắng nghe sự khác biệt về âm thanh.',
    contrastMovedToLevel: 'Cặp âm này đã lên cấp',
    tips: 'Mẹo',
    closeHelp: 'Đóng trợ giúp',
    helpLabel: 'Trợ giúp',
    doubleTapToSelectWord: 'Nhấn đúp để chọn từ này làm câu trả lời',
    doubleTapToHearAWord: 'Nhấn đúp để nghe một từ',
    doubleTapToHear: 'Nhấn đúp để nghe',
    correctYouHeard: 'Đúng — bạn đã nghe thấy',
    correctThatWas: 'Đúng — đó là',
    incorrectThisWas: 'Đó là',
    listenAndCompareWith: 'Nghe lại và so sánh với',
    trainThisContrast: 'Luyện cặp âm này',
    trainContrast: 'Luyện',
    contrastDetails: 'Chi tiết cặp âm',
    viewContrastDetails: 'Xem chi tiết cặp âm',
    practiceExamples: 'Ví dụ luyện tập',
    availableNow: 'Đang có sẵn',
    youChose: 'Bạn đã chọn',
    compareTheSounds: 'So sánh các âm',
    closeContrastDetails: 'Đóng chi tiết cặp âm',
  },
  Türkçe: {
    home: 'Ana Sayfa',
    results: 'Sonuçlar',
    info: 'Bilgiler',
    settings: 'Ayarlar',
    practicePairs: 'Çalış',
    playAudio: 'Ses çal',
    accuracyTrend: 'Son Doğruluk Trendi',
    timePracticed: 'Son alıştırma süresi',
    min: 'dakika',
    weightedAverage: 'Ağırlıklı Ortalama',
    total: 'Toplam',
    configureApp: 'Uygulamayı yapılandır',
    language: 'Dil',
    voiceSelection: 'Ses seçimi',
    systemDefault: 'Sistem varsayılanı',
    loadingVoices: 'Sesler yükleniyor...',
    noVoicesAvailable: 'Kullanılabilir ses yok',
    refresh: 'Yenile',
    appInfo: 'Uygulama bilgisi',
    version: 'Sürüm',
    build: 'Derleme',
    usAccentFemale: '🇺🇸 Amerikan Aksanı (Kadın)',
    ukAccentMale: '🇬🇧 İngiliz Aksanı (Erkek)',
    americanEnglish: 'Amerikan İngilizcesi',
    britishEnglish: 'İngiliz İngilizcesi',
    appearance: 'Görünüm',
    lightMode: 'Açık mod',
    darkMode: 'Koyu mod',
    systemMode: 'Sistem ayarı',
    useEnglishUI: 'İngilizce arayüz kullan',
    englishUIDescription: 'Arayüzü İngilizce göster',
    titleOne: 'Kulaklarınızı eğitin, dinleme becerinizi geliştirin!',
    infoOne:
      'Birçok İngilizce öğrenen kişi "ship" ve "sheep" ya da "light" ve "right" arasındaki farkı duyamaz. Bu uygulama size bu farkları duymayı öğretir.',
    titleTwo: 'Hedef',
    infoTwo:
      'Her ses farkı için en az 60 dakika pratik yapın. Başta zor olabilir ama zamanla beyniniz alışır!',
    titleThree: 'Nasıl çalışır',
    infoThree:
      '• Kelimeyi duymak için "Ses çal" tuşuna basın\n• Duyduğunuz kelimeyi seçin\n• Anında geri bildirim alın\n• İlerlemeniz kaydedilir',
    voicesAvailable: 'mevcut ses',
    voiceActive: 'aktif',
    theWordWas: 'Kelime şuydu',
    listenAgain: 'Tekrar dinle',
    correct: 'Doğru',
    incorrect: 'Yanlış',
    placementTest: 'Seviye testi',
    retakePlacement: 'Sonraki oturumda yeniden test et',
    skip: 'Atla',
    todaySession: 'Bugünkü oturum',
    dailyGoal: 'Günlük hedef',
    levelOf: 'Seviye',
    mastered: 'Tamamlandı',
    levelUnlocked: 'Seviye atladın!',
    levelCriteria: 'Artan hızlarda doğru cevap vererek seviye atlayın.',
    pairsMastered: 'Tamamlanan ses farkları',
    levelsCompleted: 'Tamamlanan seviyeler',
    placementDescription: 'Başlangıç seviyenizi belirleyin',
    placementCompleted: 'Tamamlandı',
    placementResetConfirm: 'Pratik sekmesine döndüğünüzde seviye testi başlayacak.',
    audioError: 'Ses hatası',
    audioInitializing: 'Ses sistemi hâlâ başlatılıyor. Lütfen tekrar deneyin.',
    hr: 'sa',
    helpTitle: 'Nasıl çalışılır',
    helpBody: 'Kelimeyi dinleyin ve duyduğunuza dokunun.',
    helpTipPracticeTime: 'Her ses farkını yaklaşık 60 dakika çalışın',
    helpTipSpeedIncrease: 'Seviye atladıkça hız artar',
    helpTipFocusSounds: 'Ses farkını duymaya odaklanın',
    helpButton: 'Anladım',
    onboardingTitle: "Soundwise'a Hoş Geldiniz",
    onboardingCTA: 'Dinlemeye Başla',
    onboardingBullet1: 'Kulağınızı eğitin.',
    onboardingBullet2: 'Kelimeyi dinleyin.',
    onboardingBullet3: 'Duyduğunuz kelimeyi seçin.',
    onboardingBullet4: 'Alıştırmalar ilerlemenize göre uyarlanır.',
    onboardingBullet5: 'Mikrofon gerekmez.',
    practiceThisNext: 'Sırada bunu çalış',
    practiceThisNextReason: 'Burada son doğruluğun daha düşük.',
    practiceThisNextReasonNew: 'Bu ses farkını henüz çalışmadın.',
    practiceThisNextEmpty: 'Öneri almak için birkaç ses farkı çalış.',
    noPairsFound: 'Bu kategori için ses farkı bulunamadı:',
    whichWordDidYouHear: 'Hangi kelimeyi duydunuz?',
    compareTheTwoWords: 'İki kelimeyi karşılaştır',
    play: 'Dinle',
    practicePair: 'Alıştırma çifti',
    chooseAnotherExample: 'Başka bir örnek seç',
    loading: 'Yükleniyor…',
    listenForSoundDifference: 'Ses farkını dinleyin.',
    contrastMovedToLevel: 'Bu ses farkı seviyeye yükseldi:',
    tips: 'İpuçları',
    closeHelp: 'Yardımı kapat',
    helpLabel: 'Yardım',
    doubleTapToSelectWord: 'Bu kelimeyi cevabın olarak seçmek için iki kez dokun',
    doubleTapToHearAWord: 'Bir kelime duymak için iki kez dokun',
    doubleTapToHear: 'Duymak için iki kez dokun',
    correctYouHeard: 'Doğru — duyduğunuz',
    correctThatWas: 'Doğru — bu kelimeydi',
    incorrectThisWas: 'Bu kelimeydi',
    listenAndCompareWith: 'Tekrar dinleyin ve karşılaştırın:',
    trainThisContrast: 'Bu ses farkını çalış',
    trainContrast: 'Çalış',
    contrastDetails: 'Ses karşıtlığı ayrıntıları',
    viewContrastDetails: 'Ses karşıtlığı ayrıntılarını gör',
    practiceExamples: 'Alıştırma örnekleri',
    availableNow: 'Şimdi kullanılabilir',
    youChose: 'Seçiminiz',
    compareTheSounds: 'Sesleri karşılaştırın',
    closeContrastDetails: 'Ses karşıtlığı ayrıntılarını kapat',
  },
  فارسی: {
    home: 'خانه',
    results: 'نتایج',
    info: 'اطلاعات',
    settings: 'تنظیمات',
    practicePairs: 'تمرین',
    playAudio: 'پخش صدا',
    accuracyTrend: 'روند دقت اخیر',
    timePracticed: 'زمان تمرین اخیر',
    min: 'دقیقه',
    weightedAverage: 'میانگین وزنی',
    total: 'مجموع',
    configureApp: 'تنظیم برنامه',
    language: 'زبان',
    voiceSelection: 'انتخاب صدا',
    systemDefault: 'پیش‌فرض سیستم',
    loadingVoices: 'در حال بارگذاری صداها...',
    noVoicesAvailable: 'صدایی در دسترس نیست',
    refresh: 'بروزرسانی',
    appInfo: 'اطلاعات برنامه',
    version: 'نسخه',
    build: 'شماره ساخت',
    usAccentFemale: '🇺🇸 لهجه آمریکایی (زن)',
    ukAccentMale: '🇬🇧 لهجه بریتانیایی (مرد)',
    americanEnglish: 'انگلیسی آمریکایی',
    britishEnglish: 'انگلیسی بریتانیایی',
    appearance: 'ظاهر',
    lightMode: 'حالت روشن',
    darkMode: 'حالت تاریک',
    systemMode: 'تنظیمات سیستم',
    useEnglishUI: 'استفاده از رابط کاربری انگلیسی',
    englishUIDescription: 'نمایش رابط به زبان انگلیسی',
    titleOne: 'گوش‌های خود را آموزش دهید و مهارت شنیداری را بهبود دهید!',
    infoOne:
      'بسیاری از زبان‌آموزان تفاوت "ship" و "sheep" یا "light" و "right" را تشخیص نمی‌دهند. این اپ به شما کمک می‌کند تا این تفاوت‌ها را بشنوید.',
    titleTwo: 'هدف',
    infoTwo:
      'برای هر تضاد صوتی، حداقل ۶۰ دقیقه تمرین کنید. در ابتدا ممکن است سخت باشد، اما ذهن شما با تمرین سازگار می‌شود.',
    titleThree: 'نحوه استفاده',
    infoThree:
      '• برای شنیدن کلمه، "پخش صدا" را بزنید\n• کلمه‌ای که شنیدید را انتخاب کنید\n• بلافاصله بازخورد بگیرید\n• پیشرفت شما ذخیره می‌شود',
    voicesAvailable: 'صدای موجود',
    voiceActive: 'فعال',
    theWordWas: 'کلمه بود',
    listenAgain: 'دوباره گوش کن',
    correct: 'درست',
    incorrect: 'نادرست',
    placementTest: 'آزمون تعیین سطح',
    retakePlacement: 'تکرار در جلسه بعدی',
    skip: 'رد شدن',
    todaySession: 'جلسه امروز',
    dailyGoal: 'هدف روزانه',
    levelOf: 'سطح',
    mastered: 'تسلط یافته',
    levelUnlocked: 'ارتقا سطح!',
    levelCriteria: 'با پاسخ صحیح در سرعت‌های بالاتر سطح خود را ارتقا دهید.',
    pairsMastered: 'تضادهای تسلط‌یافته',
    levelsCompleted: 'سطوح تکمیل‌شده',
    placementDescription: 'سطح شروع خود را مشخص کنید',
    placementCompleted: 'تکمیل‌شده',
    placementResetConfirm: 'آزمون تعیین سطح هنگام بازگشت به تب تمرین اجرا خواهد شد.',
    audioError: 'خطای صوتی',
    audioInitializing: 'سیستم صوتی هنوز در حال آماده‌سازی است. لطفاً دوباره تلاش کنید.',
    hr: 'ساعت',
    helpTitle: 'نحوه تمرین',
    helpBody: 'به کلمه گوش دهید و روی آنچه شنیدید ضربه بزنید.',
    helpTipPracticeTime: 'هر تضاد صوتی را حدود ۶۰ دقیقه تمرین کنید',
    helpTipSpeedIncrease: 'با بالا رفتن سطح، سرعت افزایش می‌یابد',
    helpTipFocusSounds: 'روی شنیدن تفاوت صدا تمرکز کنید',
    helpButton: 'متوجه شدم',
    onboardingTitle: 'به Soundwise خوش آمدید',
    onboardingCTA: 'شروع به گوش دادن',
    onboardingBullet1: 'گوش خود را تمرین دهید.',
    onboardingBullet2: 'به کلمه گوش دهید.',
    onboardingBullet3: 'کلمه‌ای که شنیدید را انتخاب کنید.',
    onboardingBullet4: 'تمرین‌ها با پیشرفت شما تنظیم می‌شوند.',
    onboardingBullet5: 'نیازی به میکروفون نیست.',
    practiceThisNext: 'بعدی همین را تمرین کنید',
    practiceThisNextReason: 'دقت اخیر شما اینجا کمتر است.',
    practiceThisNextReasonNew: 'هنوز این تضاد صوتی را تمرین نکرده‌اید.',
    practiceThisNextEmpty: 'چند تضاد صوتی را تمرین کنید تا پیشنهاد دریافت کنید.',
    noPairsFound: 'تضادی برای این دسته یافت نشد:',
    whichWordDidYouHear: 'کدام کلمه را شنیدید؟',
    compareTheTwoWords: 'دو کلمه را مقایسه کنید',
    play: 'پخش',
    practicePair: 'جفت تمرین',
    chooseAnotherExample: 'یک نمونه دیگر انتخاب کنید',
    loading: 'در حال بارگذاری…',
    listenForSoundDifference: 'تفاوت صدا را بشنوید.',
    contrastMovedToLevel: 'این تضاد به سطح رسید',
    tips: 'نکات',
    closeHelp: 'بستن راهنما',
    helpLabel: 'راهنما',
    doubleTapToSelectWord: 'دو بار ضربه بزنید تا این کلمه را به عنوان پاسخ انتخاب کنید',
    doubleTapToHearAWord: 'دو بار ضربه بزنید تا یک کلمه بشنوید',
    doubleTapToHear: 'دو بار ضربه بزنید تا بشنوید',
    correctYouHeard: 'درست — شنیدید',
    correctThatWas: 'درست — آن کلمه بود',
    incorrectThisWas: 'این بود',
    listenAndCompareWith: 'دوباره گوش کنید و با مقایسه کنید:',
    trainThisContrast: 'این تضاد را تمرین کنید',
    trainContrast: 'تمرین',
    contrastDetails: 'جزئیات تضاد',
    viewContrastDetails: 'مشاهده جزئیات تضاد',
    practiceExamples: 'نمونه‌های تمرین',
    availableNow: 'اکنون در دسترس',
    youChose: 'انتخاب شما',
    compareTheSounds: 'صداها را مقایسه کنید',
    closeContrastDetails: 'بستن جزئیات تضاد',
  },
  廣東話: {
    home: '首頁',
    results: '結果',
    info: '資訊',
    settings: '設定',
    practicePairs: '練習',
    playAudio: '播放音頻',
    accuracyTrend: '最近準確率趨勢',
    timePracticed: '最近練習時間',
    min: '分鐘',
    weightedAverage: '加權平均',
    total: '總計',
    configureApp: '設定應用程式',
    language: '語言',
    voiceSelection: '語音選擇',
    systemDefault: '系統預設',
    loadingVoices: '正在載入語音...',
    noVoicesAvailable: '冇可用嘅語音',
    refresh: '重新整理',
    appInfo: '應用程式資訊',
    version: '版本',
    build: '構建號',
    usAccentFemale: '🇺🇸 美國口音（女性）',
    ukAccentMale: '🇬🇧 英國口音（男性）',
    americanEnglish: '美式英語',
    britishEnglish: '英式英語',
    appearance: '外觀',
    lightMode: '淺色模式',
    darkMode: '深色模式',
    systemMode: '系統設定',
    useEnglishUI: '使用英文介面',
    englishUIDescription: '以英文顯示介面',
    titleOne: '訓練耳朵，改善聽力！',
    infoOne:
      '好多學英文嘅人都分唔清 "ship" 同 "sheep" 或 "light" 同 "right"。呢個應用程式幫你聽得出呢啲分別。',
    titleTwo: '目標',
    infoTwo: '每個對比音最少練習60分鐘。剛開始可能會難，但你嘅腦會習慣嘅！',
    titleThree: '使用方法',
    infoThree:
      '• 撳「播放音頻」去聽一個字\n• 揀返你聽到嘅字\n• 即時睇答啱定唔啱\n• 系統會自動記錄你嘅進度',
    voicesAvailable: '可用嘅聲音',
    voiceActive: '已啟用',
    theWordWas: '嗰個字係',
    listenAgain: '再聽一次',
    correct: '啱',
    incorrect: '唔啱',
    placementTest: '程度測試',
    retakePlacement: '下次練習時重新測試',
    skip: '跳過',
    todaySession: '今日練習',
    dailyGoal: '每日目標',
    levelOf: '等級',
    mastered: '已掌握',
    levelUnlocked: '升級了！',
    levelCriteria: '喺更快速度下答啱就可以升級。',
    pairsMastered: '已掌握嘅對比音',
    levelsCompleted: '已完成等級',
    placementDescription: '確定你嘅起始等級',
    placementCompleted: '已完成',    placementResetConfirm: '返回練習標籤時會重新進行程度測試。',
    audioError: '音頻錯誤',
    audioInitializing: '音頻系統仲係度初始化緊。請稍後再試。',
    hr: '小時',
    helpTitle: '點樣練習',
    helpBody: '聽個字然後撳你聽到嘅。',
    helpTipPracticeTime: '每個對比音練習大約60分鐘',
    helpTipSpeedIncrease: '升級之後速度會加快',
    helpTipFocusSounds: '集中精神聽聲音嘅分別',
    helpButton: '明白了',
    onboardingTitle: '歡迎使用 Soundwise',
    onboardingCTA: '開始聆聽',
    onboardingBullet1: '訓練你嘅耳朵。',
    onboardingBullet2: '聆聽個單詞。',
    onboardingBullet3: '揀返你聽到嘅字。',
    onboardingBullet4: '練習會根據你嘅進度調整。',
    onboardingBullet5: '唔需要麥克風。',
    practiceThisNext: '下一個練呢個',
    practiceThisNextReason: '你最近喺呢度嘅準確率較低。',
    practiceThisNextReasonNew: '你仲未練過呢個對比音。',
    practiceThisNextEmpty: '練多幾個對比音就會有推薦。',
    noPairsFound: '搵唔到呢個分類嘅對比音：',
    whichWordDidYouHear: '你聽到係哪個字？',
    compareTheTwoWords: '對比兩個字',
    play: '播放',
    practicePair: '練習配對',
    chooseAnotherExample: '選擇另一個例子',
    loading: '載入中…',
    listenForSoundDifference: '聽聲音嘅分別。',
    contrastMovedToLevel: '呢個對比音升到等級',
    tips: '提示',
    closeHelp: '關閉幫助',
    helpLabel: '幫助',
    doubleTapToSelectWord: '雙擊選擇此字作為你的答案',
    doubleTapToHearAWord: '雙擊收聽一個字',
    doubleTapToHear: '雙擊聆聽',
    correctYouHeard: '啱，你聽到嘅係',
    correctThatWas: '啱，嗰個字係',
    incorrectThisWas: '嗰個字係',
    listenAndCompareWith: '再聽一次，同以下對比：',
    trainThisContrast: '練習呢個對比音',
    trainContrast: '練習',
    contrastDetails: '對比音詳情',
    viewContrastDetails: '查看對比音詳情',
    practiceExamples: '練習例子',
    availableNow: '而家可以用',
    youChose: '你揀咗',
    compareTheSounds: '比較聲音',
    closeContrastDetails: '關閉對比音詳情',
  },
  'Bahasa Indonesia': {
    home: 'Beranda',
    results: 'Hasil',
    info: 'Informasi',
    settings: 'Pengaturan',
    practicePairs: 'Latihan',
    playAudio: 'Putar Audio',
    accuracyTrend: 'Tren Akurasi Terbaru',
    timePracticed: 'Waktu berlatih terbaru',
    min: 'menit',
    weightedAverage: 'Rata-rata tertimbang',
    total: 'Total',
    configureApp: 'Pengaturan aplikasi',
    language: 'Bahasa',
    voiceSelection: 'Pemilihan suara',
    systemDefault: 'Bawaan sistem',
    loadingVoices: 'Memuat suara...',
    noVoicesAvailable: 'Tidak ada suara tersedia',
    refresh: 'Muat ulang',
    appInfo: 'Informasi aplikasi',
    version: 'Versi',
    build: 'Nomor build',
    usAccentFemale: '🇺🇸 Aksen Amerika (Perempuan)',
    ukAccentMale: '🇬🇧 Aksen Inggris (Laki-laki)',
    americanEnglish: 'Bahasa Inggris Amerika',
    britishEnglish: 'Bahasa Inggris Britania',
    appearance: 'Tampilan',
    lightMode: 'Mode terang',
    darkMode: 'Mode gelap',
    systemMode: 'Pengaturan sistem',
    useEnglishUI: 'Gunakan antarmuka Bahasa Inggris',
    englishUIDescription: 'Tampilkan antarmuka dalam Bahasa Inggris',
    titleOne: 'Latih pendengaranmu, tingkatkan kemampuan mendengar!',
    infoOne:
      'Banyak pelajar bingung membedakan "ship" dan "sheep" atau "light" dan "right". Aplikasi ini membantu kamu melatih pendengaran untuk membedakan bunyi tersebut.',
    titleTwo: 'Tujuan',
    infoTwo:
      'Latih setiap kontras selama minimal 60 menit. Awalnya mungkin sulit, tapi otakmu akan terbiasa.',
    titleThree: 'Cara penggunaan',
    infoThree:
      '• Tekan "Putar Audio" untuk mendengarkan\n• Pilih kata yang kamu dengar\n• Dapatkan umpan balik langsung\n• Kemajuanmu akan tersimpan secara otomatis',
    voicesAvailable: 'suara tersedia',
    voiceActive: 'aktif',
    theWordWas: 'Kata itu adalah',
    listenAgain: 'Dengar lagi',
    correct: 'Benar',
    incorrect: 'Salah',
    placementTest: 'Tes penempatan',
    retakePlacement: 'Ulangi di sesi berikutnya',
    skip: 'Lewati',
    todaySession: 'Sesi hari ini',
    dailyGoal: 'Target harian',
    levelOf: 'Level',
    mastered: 'Dikuasai',
    levelUnlocked: 'Naik level!',
    levelCriteria: 'Jawab dengan benar pada kecepatan meningkat untuk naik level.',
    pairsMastered: 'Kontras yang dikuasai',
    levelsCompleted: 'Level selesai',
    placementDescription: 'Tentukan level awal Anda',
    placementCompleted: 'Selesai',
    placementResetConfirm: 'Tes penempatan akan berjalan saat Anda kembali ke tab Latihan.',
    audioError: 'Kesalahan audio',
    audioInitializing: 'Sistem audio masih sedang mempersiapkan. Silakan coba lagi.',
    hr: 'jam',
    helpTitle: 'Cara berlatih',
    helpBody: 'Dengarkan kata dan ketuk apa yang kamu dengar.',
    helpTipPracticeTime: 'Latih setiap kontras selama sekitar 60 menit',
    helpTipSpeedIncrease: 'Kecepatan meningkat seiring kenaikan level',
    helpTipFocusSounds: 'Fokus mendengar perbedaan bunyi',
    helpButton: 'Mengerti',
    onboardingTitle: 'Selamat datang di Soundwise',
    onboardingCTA: 'Mulai mendengarkan',
    onboardingBullet1: 'Latih pendengaranmu.',
    onboardingBullet2: 'Dengarkan katanya.',
    onboardingBullet3: 'Pilih kata yang kamu dengar.',
    onboardingBullet4: 'Latihan menyesuaikan dengan kemajuanmu.',
    onboardingBullet5: 'Tidak perlu mikrofon.',
    practiceThisNext: 'Latih ini berikutnya',
    practiceThisNextReason: 'Akurasi terbaru Anda di sini lebih rendah.',
    practiceThisNextReasonNew: 'Anda belum melatih kontras ini.',
    practiceThisNextEmpty: 'Latih beberapa kontras untuk mendapatkan rekomendasi.',
    noPairsFound: 'Tidak ada kontras yang ditemukan untuk',
    whichWordDidYouHear: 'Kata mana yang kamu dengar?',
    compareTheTwoWords: 'Bandingkan kedua kata',
    play: 'Putar',
    practicePair: 'Pasangan latihan',
    chooseAnotherExample: 'Pilih contoh lain',
    loading: 'Memuat…',
    listenForSoundDifference: 'Dengarkan perbedaan bunyinya.',
    contrastMovedToLevel: 'Kontras ini naik ke level',
    tips: 'Tips',
    closeHelp: 'Tutup bantuan',
    helpLabel: 'Bantuan',
    doubleTapToSelectWord: 'Ketuk dua kali untuk memilih kata ini sebagai jawabanmu',
    doubleTapToHearAWord: 'Ketuk dua kali untuk mendengar sebuah kata',
    doubleTapToHear: 'Ketuk dua kali untuk mendengar',
    correctYouHeard: 'Benar — kamu mendengar',
    correctThatWas: 'Benar — kata itu adalah',
    incorrectThisWas: 'Kata itu adalah',
    listenAndCompareWith: 'Dengarkan lagi dan bandingkan dengan',
    trainThisContrast: 'Latih kontras ini',
    trainContrast: 'Latih',
    contrastDetails: 'Detail kontras',
    viewContrastDetails: 'Lihat detail kontras',
    practiceExamples: 'Contoh latihan',
    availableNow: 'Tersedia sekarang',
    youChose: 'Pilihanmu',
    compareTheSounds: 'Bandingkan bunyinya',
    closeContrastDetails: 'Tutup detail kontras',
  },
};
