interface LanguageTranslations {
  home: string;
  results: string;
  info: string;
  settings?: string;
  practicePairs: string;
  playAudio: string;
  accuracyTrend: string;
  timePracticed: string;
  min: string;
  weightedAverage: string;
  total: string;

  titleOne: string;
  infoOne: string;
  titleTwo: string;
  infoTwo: string;
  titleThree: string;
  infoThree: string;
  
  configureApp?: string;
  language?: string;
  voiceSelection?: string;
  systemDefault?: string;
  loadingVoices?: string;
  noVoicesAvailable?: string;
  refresh?: string;
  appInfo?: string;
  version?: string;
  build?: string;
  usAccentFemale?: string;
  ukAccentMale?: string;
  americanEnglish?: string;
  britishEnglish?: string;
  appearance?: string;
  lightMode?: string;
  darkMode?: string;
  systemMode?: string;
  useEnglishUI?: string;
  englishUIDescription?: string;
  
  [key: string]: string | undefined;
}

export const alternateLanguages: Record<string, LanguageTranslations> = {
  English: {
    home: 'Home',
    results: 'Results',
    info: 'Info',
    settings: 'Settings',
    practicePairs: 'Practice Word Pairs',
    playAudio: 'Play Audio',
    accuracyTrend: 'Accuracy Trend',
    timePracticed: 'Time Practiced',
    min: 'min',
    weightedAverage: 'Weighted Average',
    total: 'Total',
    configureApp: 'Configure App',
    language: 'Language',
    voiceSelection: 'Voice Selection',
    systemDefault: 'System Default',
    loadingVoices: 'Loading voices...',
    noVoicesAvailable: 'No voices available',
    refresh: 'Refresh',
    appInfo: 'App Info',
    version: 'Version',
    build: 'Build',
    usAccentFemale: '🇺🇸 US Accent (Female)',
    ukAccentMale: '🇬🇧 UK Accent (Male)',
    americanEnglish: 'American English',
    britishEnglish: 'British English',
    appearance: 'Appearance',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    systemMode: 'System Settings',
    useEnglishUI: 'Use English UI',
    englishUIDescription: 'Display interface in English',
    titleOne: 'Train Your Ears, Transform Your Listening!',
    infoOne:
      'Many English learners struggle to distinguish between "ship" and "sheep" or "light" and "right". This app helps you train your ears to hear these subtle differences.',
    titleTwo: 'Goal',
    infoTwo:
      'Aim to practice each pair for at least 60 minutes total. It may seem difficult at first, but your brain will adapt with practice!',
    titleThree: 'How It Works',
    infoThree:
      '• Tap "Play Audio" to hear a word\n• Select the word you heard\n• Get immediate feedback\n• Track your progress over time',
  },
  日本語: {
    home: 'ホーム',
    results: '結果',
    info: '情報',
    settings: '設定',
    practicePairs: '単語ペアの練習',
    playAudio: '音声を再生',
    accuracyTrend: '正答率の推移',
    timePracticed: '練習時間',
    min: '分',
    weightedAverage: '加重平均',
    total: '合計',
    configureApp: 'アプリを設定',
    language: '言語',
    voiceSelection: '音声選択',
    systemDefault: 'システムデフォルト',
    loadingVoices: '音声を読み込み中...',
    noVoicesAvailable: '利用可能な音声がありません',
    refresh: '更新',
    appInfo: 'アプリ情報',
    version: 'バージョン',
    build: 'ビルド',
    usAccentFemale: '🇺🇸 米国アクセント（女性）',
    ukAccentMale: '🇬🇧 英国アクセント（男性）',
    americanEnglish: 'アメリカ英語',
    britishEnglish: 'イギリス英語',
    appearance: '外観',
    lightMode: 'ライトモード',
    darkMode: 'ダークモード',
    systemMode: 'システム設定',
    useEnglishUI: '英語表示を使用',
    englishUIDescription: 'インターフェースを英語で表示',
    titleOne: '耳を鍛えて、リスニング力を変えよう！',
    infoOne:
      '多くの英語学習者は "ship" と "sheep"、"light" と "right" の違いを聞き取れません。このアプリは、そうした違いを聞き取れる耳を作るためのトレーニングを提供します。',
    titleTwo: '目標',
    infoTwo:
      '各ペアを合計60分以上練習することを目指しましょう。最初は難しく感じるかもしれませんが、練習を重ねることで脳が適応してきます！',
    titleThree: 'アプリの使い方',
    infoThree:
      '•「音声を再生」をタップして単語を聞く\n• 聞こえた単語を選択\n• 正解・不正解がすぐに表示\n• 練習履歴が保存され、進捗が確認できます',
  },

  中文: {
    home: '首页',
    results: '结果',
    info: '信息',
    settings: '设置',
    practicePairs: '练习单词配对',
    playAudio: '播放音频',
    accuracyTrend: '准确率趋势',
    timePracticed: '练习时间',
    min: '分钟',
    weightedAverage: '加权平均',
    total: '总计',
    configureApp: '应用设置',
    language: '语言',
    voiceSelection: '语音选择',
    systemDefault: '系统默认',
    loadingVoices: '正在加载语音...',
    noVoicesAvailable: '没有可用的语音',
    refresh: '刷新',
    appInfo: '应用信息',
    version: '版本',
    build: '构建号',
    usAccentFemale: '🇺🇸 美国口音（女性）',
    ukAccentMale: '🇬🇧 英国口音（男性）',
    americanEnglish: '美式英语',
    britishEnglish: '英式英语',
    appearance: '外观',
    lightMode: '浅色模式',
    darkMode: '深色模式',
    systemMode: '系统设置',
    useEnglishUI: '使用英文界面',
    englishUIDescription: '以英文显示界面',
    titleOne: '训练你的耳朵，改善听力理解！',
    infoOne:
      '许多英语学习者分不清 "ship" 和 "sheep" 或 "light" 和 "right"。本应用帮助你训练听觉，分辨这些细微差别。',
    titleTwo: '目标',
    infoTwo: '每对词至少练习60分钟。起初可能很难，但练习多了，大脑会适应！',
    titleThree: '使用方法',
    infoThree:
      '• 点击“播放音频”听单词\n• 选择你听到的单词\n• 立即获得反馈\n• 记录练习进度，查看成长',
  },
  ภาษาไทย: {
    home: 'หน้าแรก',
    results: 'ผลลัพธ์',
    info: 'ข้อมูล',
    settings: 'การตั้งค่า',
    practicePairs: 'ฝึกคู่คำ',
    playAudio: 'เล่นเสียง',
    accuracyTrend: 'แนวโน้มความถูกต้อง',
    timePracticed: 'เวลาที่ฝึกฝน',
    min: 'นาที',
    weightedAverage: 'ค่าเฉลี่ยถ่วงน้ำหนัก',
    total: 'ทั้งหมด',
    configureApp: 'ตั้งค่าแอป',
    language: 'ภาษา',
    voiceSelection: 'เลือกเสียง',
    systemDefault: 'ค่าเริ่มต้นของระบบ',
    loadingVoices: 'กำลังโหลดเสียง...',
    noVoicesAvailable: 'ไม่มีเสียงที่ใช้ได้',
    refresh: 'รีเฟรช',
    appInfo: 'ข้อมูลแอป',
    version: 'เวอร์ชัน',
    build: 'บิลด์',
    usAccentFemale: '🇺🇸 สำเนียงอเมริกัน (ผู้หญิง)',
    ukAccentMale: '🇬🇧 สำเนียงอังกฤษ (ผู้ชาย)',
    americanEnglish: 'ภาษาอังกฤษอเมริกัน',
    britishEnglish: 'ภาษาอังกฤษแบบบริติช',
    appearance: 'รูปลักษณ์',
    lightMode: 'โหมดสว่าง',
    darkMode: 'โหมดมืด',
    systemMode: 'ตามระบบ',
    useEnglishUI: 'ใช้หน้าจอภาษาอังกฤษ',
    englishUIDescription: 'แสดงหน้าจอเป็นภาษาอังกฤษ',
    titleOne: 'ฝึกหูฟัง พัฒนาทักษะการฟัง!',
    infoOne:
      'ผู้เรียนภาษาอังกฤษหลายคนแยกไม่ออกระหว่างคำว่า "ship" กับ "sheep" หรือ "light" กับ "right" แอปนี้ช่วยฝึกให้คุณได้ยินความแตกต่างนั้น',
    titleTwo: 'เป้าหมาย',
    infoTwo:
      'ฝึกแต่ละคู่ให้ครบอย่างน้อย 60 นาที ไม่ต้องกังวลถ้ายังยากในตอนแรก สมองจะค่อยๆ ปรับตัว',
    titleThree: 'วิธีใช้งาน',
    infoThree:
      '• แตะ “เล่นเสียง” เพื่อฟัง\n• เลือกคำที่คุณได้ยิน\n• รับคำตอบถูก/ผิดทันที\n• ติดตามความก้าวหน้าของคุณ',
  },
  Español: {
    home: 'Inicio',
    results: 'Resultados',
    info: 'Información',
    settings: 'Configuración',
    practicePairs: 'Practicar pares de palabras',
    playAudio: 'Reproducir Audio',
    accuracyTrend: 'Tendencia de precisión',
    timePracticed: 'Tiempo practicado',
    min: 'minutos',
    weightedAverage: 'Promedio ponderado',
    total: 'Total',
    configureApp: 'Configurar aplicación',
    language: 'Idioma',
    voiceSelection: 'Selección de voz',
    systemDefault: 'Predeterminado del sistema',
    loadingVoices: 'Cargando voces...',
    noVoicesAvailable: 'No hay voces disponibles',
    refresh: 'Actualizar',
    appInfo: 'Información de la aplicación',
    version: 'Versión',
    build: 'Compilación',
    usAccentFemale: '🇺🇸 Acento estadounidense (Mujer)',
    ukAccentMale: '🇬🇧 Acento británico (Hombre)',
    americanEnglish: 'Inglés americano',
    britishEnglish: 'Inglés británico',
    appearance: 'Apariencia',
    lightMode: 'Modo claro',
    darkMode: 'Modo oscuro',
    systemMode: 'Configuración del sistema',
    useEnglishUI: 'Usar interfaz en inglés',
    englishUIDescription: 'Mostrar interfaz en inglés',
    titleOne: '¡Entrena tus oídos y mejora tu comprensión auditiva!',
    infoOne:
      'Muchos estudiantes no distinguen "ship" de "sheep" o "light" de "right". Esta app te entrena para reconocer esas diferencias.',
    titleTwo: 'Meta',
    infoTwo:
      'Practica al menos 60 minutos por cada pareja. ¡Tu oído mejorará con el tiempo!',
    titleThree: 'Cómo funciona',
    infoThree:
      '• Toca "Reproducir Audio" para escuchar\n• Elige la palabra que crees haber oído\n• Recibe retroalimentación inmediata\n• Tu progreso se guarda automáticamente',
  },
  العربية: {
    home: 'الرئيسية',
    results: 'النتائج',
    info: 'المعلومات',
    settings: 'الإعدادات',
    practicePairs: 'تدرّب على أزواج الكلمات',
    playAudio: 'تشغيل الصوت',
    accuracyTrend: 'اتجاه الدقة',
    timePracticed: 'مدة التدريب',
    min: 'دقائق',
    weightedAverage: 'المتوسط المرجح',
    total: 'المجموع',
    configureApp: 'إعدادات التطبيق',
    language: 'اللغة',
    voiceSelection: 'اختيار الصوت',
    systemDefault: 'الافتراضي للنظام',
    loadingVoices: 'جارٍ تحميل الأصوات...',
    noVoicesAvailable: 'لا تتوفر أصوات',
    refresh: 'تحديث',
    appInfo: 'معلومات التطبيق',
    version: 'الإصدار',
    build: 'رقم البناء',
    usAccentFemale: '🇺🇸 لهجة أمريكية (أنثى)',
    ukAccentMale: '🇬🇧 لهجة بريطانية (ذكر)',
    americanEnglish: 'الإنجليزية الأمريكية',
    britishEnglish: 'الإنجليزية البريطانية',
    appearance: 'المظهر',
    lightMode: 'الوضع الفاتح',
    darkMode: 'الوضع الداكن',
    systemMode: 'إعداد النظام',
    useEnglishUI: 'استخدام الواجهة الإنجليزية',
    englishUIDescription: 'عرض الواجهة باللغة الإنجليزية',
    titleOne: 'درّب أذنيك وغيّر مهارات الاستماع!',
    infoOne:
      'الكثير من متعلمي اللغة الإنجليزية لا يميزون بين "ship" و "sheep" أو "light" و "right". هذا التطبيق يساعدك على تحسين تمييز هذه الأصوات.',
    titleTwo: 'الهدف',
    infoTwo:
      'خصص 60 دقيقة على الأقل لكل زوج كلمات. لا تقلق إذا بدا الأمر صعبًا في البداية — سيتكيف دماغك مع الوقت.',
    titleThree: 'طريقة الاستخدام',
    infoThree:
      '• اضغط على "تشغيل الصوت" للاستماع\n• اختر الكلمة التي سمعتها\n• ستحصل على نتيجة فورية\n• يتم حفظ تقدمك تلقائيًا',
  },
  Русский: {
    home: 'Главная',
    results: 'Результаты',
    info: 'Информация',
    settings: 'Настройки',
    practicePairs: 'Практика пар слов',
    playAudio: 'Воспроизвести аудио',
    accuracyTrend: 'Тенденция точности',
    timePracticed: 'Время практики',
    min: 'мин',
    weightedAverage: 'Взвешенное среднее',
    total: 'Итого',
    configureApp: 'Настроить приложение',
    language: 'Язык',
    voiceSelection: 'Выбор голоса',
    systemDefault: 'По умолчанию',
    loadingVoices: 'Загрузка голосов...',
    noVoicesAvailable: 'Нет доступных голосов',
    refresh: 'Обновить',
    appInfo: 'Информация о приложении',
    version: 'Версия',
    build: 'Сборка',
    usAccentFemale: '🇺🇸 Американский акцент (Женский)',
    ukAccentMale: '🇬🇧 Британский акцент (Мужской)',
    americanEnglish: 'Американский английский',
    britishEnglish: 'Британский английский',
    appearance: 'Внешний вид',
    lightMode: 'Светлый режим',
    darkMode: 'Тёмный режим',
    systemMode: 'Настройки системы',
    useEnglishUI: 'Использовать английский интерфейс',
    englishUIDescription: 'Отображать интерфейс на английском',
    titleOne: 'Тренируй слух — улучшай понимание!',
    infoOne:
      'Многие изучающие английский не различают "ship" и "sheep" или "light" и "right". Это приложение поможет научиться их слышать.',
    titleTwo: 'Цель',
    infoTwo:
      'Практикуй каждую пару минимум 60 минут. Сложно сначала — но мозг привыкнет!',
    titleThree: 'Как это работает',
    infoThree:
      '• Нажми “Воспроизвести аудио”\n• Выбери слово, которое услышал\n• Мгновенная обратная связь\n• Прогресс сохраняется',
  },
  한국어: {
    home: '홈',
    results: '결과',
    info: '정보',
    settings: '설정',
    practicePairs: '단어 쌍 연습',
    playAudio: '오디오 재생',
    accuracyTrend: '정확도 추이',
    timePracticed: '연습 시간',
    min: '분',
    weightedAverage: '가중 평균',
    total: '총합',
    configureApp: '앱 설정',
    language: '언어',
    voiceSelection: '음성 선택',
    systemDefault: '시스템 기본값',
    loadingVoices: '음성 로딩 중...',
    noVoicesAvailable: '사용 가능한 음성이 없습니다',
    refresh: '새로고침',
    appInfo: '앱 정보',
    version: '버전',
    build: '빌드',
    usAccentFemale: '🇺🇸 미국 악센트 (여성)',
    ukAccentMale: '🇬🇧 영국 악센트 (남성)',
    americanEnglish: '미국 영어',
    britishEnglish: '영국 영어',
    appearance: '외관',
    lightMode: '라이트 모드',
    darkMode: '다크 모드',
    systemMode: '시스템 설정',
    useEnglishUI: '영어 UI 사용',
    englishUIDescription: '인터페이스를 영어로 표시',
    titleOne: '귀를 훈련하여 듣기 능력을 향상시키세요!',
    infoOne:
      '많은 영어 학습자들이 "ship"과 "sheep", "light"과 "right"의 차이를 구별하지 못합니다. 이 앱은 그런 구별을 가능하게 도와줍니다.',
    titleTwo: '목표',
    infoTwo:
      '각 단어 쌍을 최소 60분 이상 연습하세요. 처음에는 어려워도 점점 더 잘 들릴 거예요!',
    titleThree: '사용 방법',
    infoThree:
      '• "오디오 재생"을 눌러 단어 듣기\n• 들은 단어 선택하기\n• 즉시 피드백 받기\n• 진행 상황 자동 저장',
  },
  'हिंदी/اردو': {
    home: 'होम/ہوم',
    results: 'परिणाम/نتائج',
    info: 'जानकारी/معلومات',
    settings: 'सेटिंग्स/ترتیبات',
    practicePairs: 'शब्द जोड़ी अभ्यास/لفظی جوڑوں کی مشق',
    playAudio: 'ऑडियो चलाएँ/آڈیو چلائیں',
    accuracyTrend: 'सटीकता प्रवृत्ति/درستگی کا رجحان',
    timePracticed: 'अभ्यास का समय/مشق کا وقت',
    min: 'मिनट/منٹ',
    weightedAverage: 'भारित औसत/وزنی اوسط',
    total: 'कुल/کل',
    configureApp: 'ऐप सेटिंग्स/ایپ ترتیبات',
    language: 'भाषा/زبان',
    voiceSelection: 'आवाज़ चयन/آواز کا انتخاب',
    systemDefault: 'सिस्टम डिफ़ॉल्ट/سسٹم ڈیفالٹ',
    loadingVoices: 'आवाज़ें लोड हो रही हैं.../آوازیں لوڈ ہو رہی ہیں...',
    noVoicesAvailable: 'कोई आवाज़ उपलब्ध नहीं/کوئی آواز دستیاب نہیں',
    refresh: 'रीफ़्रेश/ریفریش',
    appInfo: 'ऐप जानकारी/ایپ کی معلومات',
    version: 'संस्करण/ورژن',
    build: 'बिल्ड/بلڈ',
    usAccentFemale: '🇺🇸 अमेरिकी उच्चारण (महिला)/امریکی لہجہ (خاتون)',
    ukAccentMale: '🇬🇧 ब्रिटिश उच्चारण (पुरुष)/برطانوی لہجہ (مرد)',
    americanEnglish: 'अमेरिकी अंग्रेज़ी/امریکی انگریزی',
    britishEnglish: 'ब्रिटिश अंग्रेज़ी/برطانوی انگریزی',
    appearance: 'दिखावट/ظہور',
    lightMode: 'लाइट मोड/لائٹ موڈ',
    darkMode: 'डार्क मोड/ڈارک موڈ',
    systemMode: 'सिस्टम सेटिंग/سسٹم کی ترتیب',
    useEnglishUI: 'अंग्रेज़ी UI उपयोग करें/انگریزی UI استعمال کریں',
    englishUIDescription: 'इंटरफ़ेस अंग्रेज़ी में दिखाएं/انٹرفیس انگریزی میں دکھائیں',
    titleOne: 'अपने कानों को प्रशिक्षित करें, सुनने की क्षमता सुधारें!/!اپنے کانوں کو تربیت دیں، سننے کی صلاحیت بہتر بنائیں',
    infoOne:
      '"ship" और "sheep" या "light" और "right" जैसे शब्दों में फर्क करना कठिन हो सकता है। यह ऐप आपको वह फर्क सुनने में मदद करता है।/"ship" اور "sheep" یا "light" اور "right" جیسے الفاظ میں فرق کرنا مشکل ہو سکتا ہے۔ یہ ایپ آپ کو یہ فرق سننے میں مدد کرتی ہے۔',
    titleTwo: 'लक्ष्य/ہدف',
    infoTwo:
      'हर जोड़ी पर कम से कम 60 मिनट अभ्यास करें। शुरुआत में कठिन लग सकता है, लेकिन अभ्यास से सुधार होगा!/ہر جوڑے پر کم از کم 60 منٹ مشق کریں۔ شروع میں مشکل لگ سکتا ہے، لیکن مشق سے بہتری آئے گی!',
    titleThree: 'यह कैसे काम करता है/یہ کیسے کام کرتا ہے',
    infoThree:
      '• "ऑडियो चलाएँ" पर टैप करें\n• सुनी हुई शब्द चुनें\n• तुरंत प्रतिक्रिया पाएं\n• आपकी प्रगति सहेजी जाती है/• "آڈیو چلائیں" پر ٹیپ کریں\n• سنا ہوا لفظ چنیں\n• فوری ردعمل حاصل کریں\n• آپ کی پیشرفت خود بخود محفوظ ہوتی ہے',
  },
  Português: {
    home: 'Início',
    results: 'Resultados',
    info: 'Informações',
    settings: 'Configurações',
    practicePairs: 'Praticar pares de palavras',
    playAudio: 'Reproduzir áudio',
    accuracyTrend: 'Tendência de precisão',
    timePracticed: 'Tempo praticado',
    min: 'minutos',
    weightedAverage: 'Média ponderada',
    total: 'Total',
    configureApp: 'Configurar aplicativo',
    language: 'Idioma',
    voiceSelection: 'Seleção de voz',
    systemDefault: 'Padrão do sistema',
    loadingVoices: 'Carregando vozes...',
    noVoicesAvailable: 'Nenhuma voz disponível',
    refresh: 'Atualizar',
    appInfo: 'Informações do aplicativo',
    version: 'Versão',
    build: 'Compilação',
    usAccentFemale: '🇺🇸 Sotaque americano (Feminino)',
    ukAccentMale: '🇬🇧 Sotaque britânico (Masculino)',
    americanEnglish: 'Inglês americano',
    britishEnglish: 'Inglês britânico',
    appearance: 'Aparência',
    lightMode: 'Modo claro',
    darkMode: 'Modo escuro',
    systemMode: 'Configuração do sistema',
    useEnglishUI: 'Usar interface em inglês',
    englishUIDescription: 'Exibir interface em inglês',
    titleOne: 'Treine seus ouvidos, melhore sua escuta!',
    infoOne:
      'Muitos alunos de inglês não distinguem "ship" de "sheep" ou "light" de "right". Este app ajuda a treinar sua audição para perceber essas diferenças.',
    titleTwo: 'Objetivo',
    infoTwo:
      'Pratique pelo menos 60 minutos com cada par. No início pode ser difícil, mas seu cérebro vai se adaptar!',
    titleThree: 'Como funciona',
    infoThree:
      '• Toque em "Reproduzir áudio" para ouvir\n• Escolha a palavra que você ouviu\n• Receba feedback imediato\n• Acompanhe seu progresso automaticamente',
  },
  'Tiếng Việt': {
    home: 'Trang chủ',
    results: 'Kết quả',
    info: 'Thông tin',
    settings: 'Cài đặt',
    practicePairs: 'Luyện tập cặp từ',
    playAudio: 'Phát âm thanh',
    accuracyTrend: 'Xu hướng độ chính xác',
    timePracticed: 'Thời gian luyện tập',
    min: 'phút',
    weightedAverage: 'Trung bình trọng số',
    total: 'Tổng cộng',
    configureApp: 'Thiết lập ứng dụng',
    language: 'Ngôn ngữ',
    voiceSelection: 'Chọn giọng nói',
    systemDefault: 'Mặc định hệ thống',
    loadingVoices: 'Đang tải giọng nói...',
    noVoicesAvailable: 'Không có giọng nói nào',
    refresh: 'Làm mới',
    appInfo: 'Thông tin ứng dụng',
    version: 'Phiên bản',
    build: 'Bản build',
    usAccentFemale: '🇺🇸 Giọng Mỹ (Nữ)',
    ukAccentMale: '🇬🇧 Giọng Anh (Nam)',
    americanEnglish: 'Tiếng Anh Mỹ',
    britishEnglish: 'Tiếng Anh Anh Quốc',
    appearance: 'Giao diện',
    lightMode: 'Chế độ sáng',
    darkMode: 'Chế độ tối',
    systemMode: 'Cài đặt hệ thống',
    useEnglishUI: 'Sử dụng giao diện tiếng Anh',
    englishUIDescription: 'Hiển thị giao diện bằng tiếng Anh',
    titleOne: 'Luyện tai, cải thiện kỹ năng nghe!',
    infoOne:
      'Nhiều người học tiếng Anh không phân biệt được "ship" và "sheep", hoặc "light" và "right". Ứng dụng này giúp bạn luyện nghe các âm thanh khó phân biệt.',
    titleTwo: 'Mục tiêu',
    infoTwo:
      'Dành ít nhất 60 phút luyện tập mỗi cặp. Ban đầu có thể khó, nhưng não bạn sẽ thích nghi dần!',
    titleThree: 'Cách sử dụng',
    infoThree:
      '• Nhấn "Phát âm thanh" để nghe\n• Chọn từ bạn nghe thấy\n• Nhận phản hồi ngay lập tức\n• Tiến độ luyện tập sẽ được lưu lại',
  },
  Türkçe: {
    home: 'Ana Sayfa',
    results: 'Sonuçlar',
    info: 'Bilgiler',
    settings: 'Ayarlar',
    practicePairs: 'Kelime Çiftlerini Çalış',
    playAudio: 'Ses çal',
    accuracyTrend: 'Doğruluk Trendi',
    timePracticed: 'Alıştırma süresi',
    min: 'dakika',
    weightedAverage: 'Ağırlıklı Ortalama',
    total: 'Toplam',
    configureApp: 'Uygulamayı yapılandır',
    language: 'Dil',
    voiceSelection: 'Ses seçimi',
    systemDefault: 'Sistem varsayılanı',
    loadingVoices: 'Sesler yükleniyor...',
    noVoicesAvailable: 'Kullanılabilir ses yok',
    refresh: 'Yenile',
    appInfo: 'Uygulama bilgisi',
    version: 'Sürüm',
    build: 'Derleme',
    usAccentFemale: '🇺🇸 Amerikan Aksanı (Kadın)',
    ukAccentMale: '🇬🇧 İngiliz Aksanı (Erkek)',
    americanEnglish: 'Amerikan İngilizcesi',
    britishEnglish: 'İngiliz İngilizcesi',
    appearance: 'Görünüm',
    lightMode: 'Açık mod',
    darkMode: 'Koyu mod',
    systemMode: 'Sistem ayarı',
    useEnglishUI: 'İngilizce arayüz kullan',
    englishUIDescription: 'Arayüzü İngilizce göster',
    titleOne: 'Kulaklarınızı eğitin, dinleme becerinizi geliştirin!',
    infoOne:
      'Birçok İngilizce öğrenen kişi "ship" ve "sheep" ya da "light" ve "right" arasındaki farkı duyamaz. Bu uygulama size bu farkları duymayı öğretir.',
    titleTwo: 'Hedef',
    infoTwo:
      'Her eşleşme için en az 60 dakika pratik yapın. Başta zor olabilir ama zamanla beyniniz alışır!',
    titleThree: 'Nasıl çalışır',
    infoThree:
      '• Kelimeyi duymak için "Ses çal" tuşuna basın\n• Duyduğunuz kelimeyi seçin\n• Anında geri bildirim alın\n• İlerlemeniz kaydedilir',
  },
  فارسی: {
    home: 'خانه',
    results: 'نتایج',
    info: 'اطلاعات',
    settings: 'تنظیمات',
    practicePairs: 'تمرین جفت کلمات',
    playAudio: 'پخش صدا',
    accuracyTrend: 'روند دقت',
    timePracticed: 'زمان تمرین',
    min: 'دقیقه',
    weightedAverage: 'میانگین وزنی',
    total: 'مجموع',
    configureApp: 'تنظیم برنامه',
    language: 'زبان',
    voiceSelection: 'انتخاب صدا',
    systemDefault: 'پیش‌فرض سیستم',
    loadingVoices: 'در حال بارگذاری صداها...',
    noVoicesAvailable: 'صدایی در دسترس نیست',
    refresh: 'بروزرسانی',
    appInfo: 'اطلاعات برنامه',
    version: 'نسخه',
    build: 'شماره ساخت',
    usAccentFemale: '🇺🇸 لهجه آمریکایی (زن)',
    ukAccentMale: '🇬🇧 لهجه بریتانیایی (مرد)',
    americanEnglish: 'انگلیسی آمریکایی',
    britishEnglish: 'انگلیسی بریتانیایی',
    appearance: 'ظاهر',
    lightMode: 'حالت روشن',
    darkMode: 'حالت تاریک',
    systemMode: 'تنظیمات سیستم',
    useEnglishUI: 'استفاده از رابط کاربری انگلیسی',
    englishUIDescription: 'نمایش رابط به زبان انگلیسی',
    titleOne: 'گوش‌های خود را آموزش دهید و مهارت شنیداری را بهبود دهید!',
    infoOne:
      'بسیاری از زبان‌آموزان تفاوت "ship" و "sheep" یا "light" و "right" را تشخیص نمی‌دهند. این اپ به شما کمک می‌کند تا این تفاوت‌ها را بشنوید.',
    titleTwo: 'هدف',
    infoTwo:
      'برای هر جفت کلمه، حداقل ۶۰ دقیقه تمرین کنید. در ابتدا ممکن است سخت باشد، اما ذهن شما با تمرین سازگار می‌شود.',
    titleThree: 'نحوه استفاده',
    infoThree:
      '• برای شنیدن کلمه، "پخش صدا" را بزنید\n• کلمه‌ای که شنیدید را انتخاب کنید\n• بلافاصله بازخورد بگیرید\n• پیشرفت شما ذخیره می‌شود',
  },
  廣東話: {
    home: '首頁',
    results: '結果',
    info: '資訊',
    settings: '設定',
    practicePairs: '練習詞語配對',
    playAudio: '播放音頻',
    accuracyTrend: '準確率趨勢',
    timePracticed: '練習時間',
    min: '分鐘',
    weightedAverage: '加權平均',
    total: '總計',
    configureApp: '設定應用程式',
    language: '語言',
    voiceSelection: '語音選擇',
    systemDefault: '系統預設',
    loadingVoices: '正在載入語音...',
    noVoicesAvailable: '冇可用嘅語音',
    refresh: '重新整理',
    appInfo: '應用程式資訊',
    version: '版本',
    build: '構建號',
    usAccentFemale: '🇺🇸 美國口音（女性）',
    ukAccentMale: '🇬🇧 英國口音（男性）',
    americanEnglish: '美式英語',
    britishEnglish: '英式英語',
    appearance: '外觀',
    lightMode: '淺色模式',
    darkMode: '深色模式',
    systemMode: '系統設定',
    useEnglishUI: '使用英文介面',
    englishUIDescription: '以英文顯示介面',
    titleOne: '訓練耳朵，改善聽力！',
    infoOne:
      '好多學英文嘅人都分唔清 "ship" 同 "sheep" 或 "light" 同 "right"。呢個應用程式幫你聽得出呢啲分別。',
    titleTwo: '目標',
    infoTwo: '每對最少練習60分鐘。剛開始可能會難，但你嘅腦會習慣嘅！',
    titleThree: '使用方法',
    infoThree:
      '• 撳「播放音頻」去聽一個字\n• 揀返你聽到嘅字\n• 即時睇答啱定唔啱\n• 系統會自動記錄你嘅進度',
  },
  'Bahasa Indonesia': {
    home: 'Beranda',
    results: 'Hasil',
    info: 'Informasi',
    settings: 'Pengaturan',
    practicePairs: 'Latihan Pasangan Kata',
    playAudio: 'Putar Audio',
    accuracyTrend: 'Tren Akurasi',
    timePracticed: 'Waktu berlatih',
    min: 'menit',
    weightedAverage: 'Rata-rata tertimbang',
    total: 'Total',
    configureApp: 'Pengaturan aplikasi',
    language: 'Bahasa',
    voiceSelection: 'Pemilihan suara',
    systemDefault: 'Bawaan sistem',
    loadingVoices: 'Memuat suara...',
    noVoicesAvailable: 'Tidak ada suara tersedia',
    refresh: 'Muat ulang',
    appInfo: 'Informasi aplikasi',
    version: 'Versi',
    build: 'Nomor build',
    usAccentFemale: '🇺🇸 Aksen Amerika (Perempuan)',
    ukAccentMale: '🇬🇧 Aksen Inggris (Laki-laki)',
    americanEnglish: 'Bahasa Inggris Amerika',
    britishEnglish: 'Bahasa Inggris Britania',
    appearance: 'Tampilan',
    lightMode: 'Mode terang',
    darkMode: 'Mode gelap',
    systemMode: 'Pengaturan sistem',
    useEnglishUI: 'Gunakan antarmuka Bahasa Inggris',
    englishUIDescription: 'Tampilkan antarmuka dalam Bahasa Inggris',
    titleOne: 'Latih pendengaranmu, tingkatkan kemampuan mendengar!',
    infoOne:
      'Banyak pelajar bingung membedakan "ship" dan "sheep" atau "light" dan "right". Aplikasi ini membantu kamu melatih pendengaran untuk membedakan bunyi tersebut.',
    titleTwo: 'Tujuan',
    infoTwo:
      'Latih setiap pasangan kata selama minimal 60 menit. Awalnya mungkin sulit, tapi otakmu akan terbiasa.',
    titleThree: 'Cara penggunaan',
    infoThree:
      '• Tekan "Putar Audio" untuk mendengarkan\n• Pilih kata yang kamu dengar\n• Dapatkan umpan balik langsung\n• Kemajuanmu akan tersimpan secara otomatis',
  },
};
