export const DEFAULT_LANGUAGE_CODE = 'en';

export const localeLanguageMap: Record<string, string> = {
  en: 'English',
  ja: '日本語',
  zh: '中文',
  th: 'ภาษาไทย',
  ko: '한국어',
  hi: 'हिन्दी / اردو',
  ur: 'हिन्दी / اردو',
  pt: 'Português',
  tr: 'Türkçe',
  yue: '廣東話',
  es: 'Español',
  ar: 'العربية',
  ru: 'Русский',
  vi: 'Tiếng Việt',
  fa: 'فارسی',
  id: 'Bahasa Indonesia',
};

export const regionLanguageMap: Record<string, string> = {
  JP: '日本語',
  CN: '中文',
  TW: '中文',
  HK: '廣東話',
  TH: 'ภาษาไทย',
  KR: '한국어',
  IN: 'हिन्दी / اردو',
  PK: 'हिन्दी / اردو',
  PT: 'Português',
  BR: 'Português',
  TR: 'Türkçe',
  ES: 'Español',
  MX: 'Español',
  AR: 'Español',
  CO: 'Español',
  CL: 'Español',
  PE: 'Español',
  VE: 'Español',
  SA: 'العربية',
  AE: 'العربية',
  EG: 'العربية',
  IQ: 'العربية',
  JO: 'العربية',
  KW: 'العربية',
  LB: 'العربية',
  RU: 'Русский',
  VN: 'Tiếng Việt',
  IR: 'فارسی',
  ID: 'Bahasa Indonesia',
};

export const englishSpeakingRegions = new Set([
  'US',
  'GB',
  'CA',
  'AU',
  'NZ',
  'IE',
  'ZA',
  'SG',
]);
